// Small site-chrome strings per language (marketing copy itself comes from
// fastlane metadata via src/generated/content.json).
export type ChromeStrings = {
  features: string;
  screenshots: string;
  languages: string;
  support: string;
  privacy: string;
  terms: string;
  download: string;
  comingSoon: string;
  contact: string;
};

export const CHROME: Record<string, ChromeStrings> = {
  en: {
    features: "Features",
    screenshots: "Screenshots",
    languages: "Languages",
    support: "Support",
    privacy: "Privacy Policy",
    terms: "Terms & Conditions",
    download: "Download on the App Store",
    comingSoon: "Coming soon to the App Store",
    contact: "Contact",
  },
  "zh-Hant": {
    features: "功能特色",
    screenshots: "畫面預覽",
    languages: "支援語言",
    support: "支援",
    privacy: "隱私權政策",
    terms: "服務條款",
    download: "前往 App Store 下載",
    comingSoon: "即將上架 App Store",
    contact: "聯絡我們",
  },
  ja: {
    features: "機能",
    screenshots: "スクリーンショット",
    languages: "対応言語",
    support: "サポート",
    privacy: "プライバシーポリシー",
    terms: "利用規約",
    download: "App Storeでダウンロード",
    comingSoon: "まもなくApp Storeに登場",
    contact: "お問い合わせ",
  },
  ko: {
    features: "기능",
    screenshots: "스크린샷",
    languages: "지원 언어",
    support: "지원",
    privacy: "개인정보 처리방침",
    terms: "이용약관",
    download: "App Store에서 다운로드",
    comingSoon: "곧 App Store 출시",
    contact: "문의하기",
  },
  es: {
    features: "Funciones",
    screenshots: "Capturas",
    languages: "Idiomas",
    support: "Soporte",
    privacy: "Política de privacidad",
    terms: "Términos y condiciones",
    download: "Descargar en el App Store",
    comingSoon: "Muy pronto en el App Store",
    contact: "Contacto",
  },
  fr: {
    features: "Fonctionnalités",
    screenshots: "Captures d'écran",
    languages: "Langues",
    support: "Assistance",
    privacy: "Politique de confidentialité",
    terms: "Conditions d'utilisation",
    download: "Télécharger dans l'App Store",
    comingSoon: "Bientôt sur l'App Store",
    contact: "Contact",
  },
  de: {
    features: "Funktionen",
    screenshots: "Screenshots",
    languages: "Sprachen",
    support: "Support",
    privacy: "Datenschutzerklärung",
    terms: "Nutzungsbedingungen",
    download: "Im App Store laden",
    comingSoon: "Bald im App Store",
    contact: "Kontakt",
  },
  it: {
    features: "Funzioni",
    screenshots: "Schermate",
    languages: "Lingue",
    support: "Supporto",
    privacy: "Informativa sulla privacy",
    terms: "Termini e condizioni",
    download: "Scarica sull'App Store",
    comingSoon: "Presto sull'App Store",
    contact: "Contatti",
  },
  pt: {
    features: "Recursos",
    screenshots: "Capturas de tela",
    languages: "Idiomas",
    support: "Suporte",
    privacy: "Política de privacidade",
    terms: "Termos e condições",
    download: "Baixar na App Store",
    comingSoon: "Em breve na App Store",
    contact: "Contato",
  },
  ru: {
    features: "Функции",
    screenshots: "Скриншоты",
    languages: "Языки",
    support: "Поддержка",
    privacy: "Политика конфиденциальности",
    terms: "Условия использования",
    download: "Загрузить в App Store",
    comingSoon: "Скоро в App Store",
    contact: "Связаться",
  },
  hi: {
    features: "विशेषताएँ",
    screenshots: "स्क्रीनशॉट",
    languages: "भाषाएँ",
    support: "सहायता",
    privacy: "गोपनीयता नीति",
    terms: "नियम और शर्तें",
    download: "App Store से डाउनलोड करें",
    comingSoon: "जल्द ही App Store पर",
    contact: "संपर्क करें",
  },
  id: {
    features: "Fitur",
    screenshots: "Tangkapan layar",
    languages: "Bahasa",
    support: "Dukungan",
    privacy: "Kebijakan privasi",
    terms: "Syarat dan ketentuan",
    download: "Unduh di App Store",
    comingSoon: "Segera hadir di App Store",
    contact: "Kontak",
  },
  vi: {
    features: "Tính năng",
    screenshots: "Ảnh chụp màn hình",
    languages: "Ngôn ngữ",
    support: "Hỗ trợ",
    privacy: "Chính sách quyền riêng tư",
    terms: "Điều khoản sử dụng",
    download: "Tải trên App Store",
    comingSoon: "Sắp có trên App Store",
    contact: "Liên hệ",
  },
  th: {
    features: "ฟีเจอร์",
    screenshots: "ภาพหน้าจอ",
    languages: "ภาษา",
    support: "ฝ่ายสนับสนุน",
    privacy: "นโยบายความเป็นส่วนตัว",
    terms: "ข้อกำหนดการใช้งาน",
    download: "ดาวน์โหลดบน App Store",
    comingSoon: "เร็ว ๆ นี้บน App Store",
    contact: "ติดต่อเรา",
  },
  tr: {
    features: "Özellikler",
    screenshots: "Ekran görüntüleri",
    languages: "Diller",
    support: "Destek",
    privacy: "Gizlilik politikası",
    terms: "Kullanım koşulları",
    download: "App Store'dan indir",
    comingSoon: "Yakında App Store'da",
    contact: "İletişim",
  },
  pl: {
    features: "Funkcje",
    screenshots: "Zrzuty ekranu",
    languages: "Języki",
    support: "Wsparcie",
    privacy: "Polityka prywatności",
    terms: "Regulamin",
    download: "Pobierz w App Store",
    comingSoon: "Wkrótce w App Store",
    contact: "Kontakt",
  },
};
