import { STORAGE_KEYS, SUPPORTED_LANGUAGES } from "@/utils/constants";
import type { ResolvedLanguage } from "@/utils/formatting";
import {
  GLOSSARY_TRANSLATION_DE,
  GLOSSARY_TRANSLATION_EN,
  GLOSSARY_TRANSLATION_ES,
  GLOSSARY_TRANSLATION_FR,
  GLOSSARY_TRANSLATION_JA,
  GLOSSARY_TRANSLATION_ZH,
} from "@/utils/glossary-i18n";
import { logger } from "@/utils/logger";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Localization from "expo-localization";
import React, {
    createContext,
    useContext,
    useEffect,
    useMemo,
    useState,
} from "react";

export type Language = "en" | "zh" | "es" | "fr" | "de" | "ja" | "device";

export interface LanguageContextType {
  language: Language;
  resolvedLanguage: ResolvedLanguage;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
}

// Detect device locale and map to supported languages
const getDeviceLanguage = (): ResolvedLanguage => {
  try {
    // Get the device locales from expo-localization
    const locales = Localization.getLocales();

    // Ensure locales is an array and has at least one element
    if (!Array.isArray(locales) || locales.length === 0) {
      logger.warn("No device locales found, falling back to English");
      return "en";
    }

    // Use the first locale (primary device language)
    const primaryLocale = locales[0];
    if (!primaryLocale) {
      logger.warn("Primary locale is undefined, falling back to English");
      return "en";
    }

    // Extract language code (e.g., "en" from "en-US")
    let langCode: string | null = null;

    // Try languageCode first (most reliable)
    if (primaryLocale.languageCode) {
      langCode = primaryLocale.languageCode.toLowerCase();
    }
    // Fallback to extracting from languageTag (e.g., "en-US" -> "en")
    else if (primaryLocale.languageTag) {
      const parts = primaryLocale.languageTag.split("-");
      if (parts.length > 0) {
        langCode = parts[0].toLowerCase();
      }
    }

    // If we still don't have a language code, fall back to English
    if (!langCode) {
      logger.warn(
        "Could not extract language code from locale, falling back to English",
        { locale: primaryLocale }
      );
      return "en";
    }

    // Map device language codes to our supported languages
    // Fallback to "en" if the device language is not supported
    const languageMap: Record<string, ResolvedLanguage> = {
      en: "en",
      zh: "zh", // Supports both zh-Hans and zh-Hant
      es: "es",
      fr: "fr",
      de: "de",
      ja: "ja",
    };

    const resolvedLang = languageMap[langCode];
    if (!resolvedLang) {
      logger.debug(
        "Device language is not supported, falling back to English",
        { langCode }
      );
      return "en";
    }

    return resolvedLang;
  } catch (error) {
    logger.error("Failed to detect device language", error);
    // Always fall back to English on any error
    return "en";
  }
};

const translations: Record<ResolvedLanguage, Record<string, string>> = {
  en: {
    accounting: "Accounting",
    statistics: "Statistics",
    diagram: "Diagram",
    total: "Total",
    count: "Count",
    flashAccounting: "Black White Accounting",
    noConsumptionsYet: "No consumptions yet",
    addFirstExpense: "Add your first expense above",
    amount: "Amount",
    description: "Description (optional)",
    noDescription: "No description",
    add: "Add",
    byDay: "By Day",
    byMonth: "By Month",
    time: "Time",
    sort: "Sort",
    all: "All",
    today: "Today",
    week: "Week",
    month: "Month",
    year: "Year",
    newest: "Newest",
    oldest: "Oldest",
    highest: "Highest",
    lowest: "Lowest",
    today_label: "Today",
    yesterday: "Yesterday",
    items: "items",
    item: "item",
    noConsumptions: "No consumptions found",
    logDay: "Log Day",
    rateThisApp: "Rate This App",
    settings: "Settings",
    exportCSV: "Export to CSV",
    selectLanguage: "Select Language",
    clearHistory: "Clear All History",
    clearHistoryConfirm: "Are you sure you want to clear all history?",
    cancel: "Cancel",
    confirm: "Confirm",
    english: "English",
    chinese: "Traditional Chinese",
    spanish: "Spanish",
    french: "French",
    german: "German",
    japanese: "Japanese",
    device: "Device Language",
    exportSuccess: "CSV exported successfully!",
    exportError: "Failed to export CSV",
    clearSuccess: "History cleared successfully",
    exportSharingUnavailable: "Sharing is not available on this device",
    errorClearHistoryFailed: "Failed to clear history",
    authFeatureTitle: "Auth feature",
    authFeatureSubtitle: "Optional sign-in. Local-first by default.",
    authStatusSignedIn: "Signed in",
    authStatusSignedOut: "Not signed in",
    authOptionalNote: "You can keep using the app without signing in.",
    authContinueGoogle: "Continue with Google",
    authContinueApple: "Continue with Apple",
    authContinueFacebook: "Continue with Facebook",
    authSignOut: "Sign out",
    authErrorTitle: "Sign-in failed",
    authErrorMessage: "Please try again.",
    authNotConfiguredTitle: "Auth not configured",
    authNotConfiguredMessage: "Firebase auth is not configured for this build.",
    cloudSyncTitle: "Cloud Sync (Pro)",
    cloudSyncActive: "Active — saving to cloud",
    cloudSyncStatusReady: "Ready — device and cloud match",
    cloudSyncStatusSyncing: "Syncing now",
    cloudSyncStatusPending: "Pending local changes",
    cloudSyncStatusError: "Sync needs attention",
    cloudSyncLockedSignedIn: "Signed in — upgrade to enable cloud sync",
    cloudSyncLockedSignedOut: "Sign in + upgrade to enable cloud sync",
    cloudSyncLockedPaid: "Purchased — sign in to use cloud sync",
    cloudSyncPendingDetail:
      "Local changes are safe on this device. Push this device to cloud to finish syncing.",
    cloudSyncErrorDetail:
      "Cloud sync could not be checked. Review your connection or retry manually.",
    cloudSyncLastSynced: "Last successful sync: {date}",
    cloudSyncNeverSynced: "No successful cloud sync yet",
    cloudSyncUpgradeCta: "Unlock Cloud Sync",
    cloudSyncMonthlyCta: "Get Monthly Cloud Sync",
    cloudSyncAnnualCta: "Get Yearly Cloud Sync",
    cloudSyncRestoreCta: "Restore Purchase",
    cloudSyncRetryCta: "Retry pending sync",
    cloudSyncRetryDetail: "Replace cloud data with this device to finish pending sync.",
    cloudSyncSyncCta: "Push this device to cloud",
    cloudSyncSyncDetail: "Replace cloud data with this device, then refresh from cloud.",
    cloudSyncSyncConfirm: "Replace your cloud data with the records currently on this device?",
    cloudSyncSyncDone: "Cloud replaced with {count} local records.",
    cloudSyncSyncFailed: "Cloud sync failed. Your local changes are still saved on this device.",
    cloudSyncPullCta: "Replace this device from cloud",
    cloudSyncPullDetail: "Discard pending local changes and download the latest cloud copy.",
    cloudSyncPullConfirm:
      "Replace the records on this device with the latest cloud data? Pending local changes on this device will be discarded.",
    cloudSyncPullDone: "Downloaded {count} cloud records to this device.",
    cloudSyncPullFailed: "Cloud download failed. Your current local data was kept.",
    iapNotReadyTitle: "Purchase not set up",
    iapNotReadyMessage:
      "Purchases are not configured for this build. Add RevenueCat keys and rebuild the app.",
    iapPackageUnavailableMessage: "This plan is not available in the current store offering.",
    iapErrorTitle: "Purchase failed",
    iapErrorMessage: "Please try again later.",
    localLimitTitle: "Local storage limit",
    localLimitValue: "{count} / {limit} records on this device",
    localLimitReachedTitle: "Limit reached",
    localLimitReachedMessage:
      "You reached the free local limit. Upgrade to Pro and sign in to unlock unlimited cloud storage.",
    localLimitReachedLocalOnlyMessage:
      "You reached the local record limit for this build. Remove some records to keep using this device.",
    storageUpgradeTitle: "Upgrade Storage Plan",
    storageUpgradeSubtitle: "Compare Basic, Plus, and Pro storage options.",
    storageUpgradeEyebrow: "Storage",
    storageUpgradeIntro:
      "Choose the plan that fits how you keep records: free local use, unlimited local storage, or cloud sync for multiple devices and shared books.",
    storagePlanCurrentBasic: "Current plan: Basic",
    storagePlanCurrentPlus: "Current plan: Plus",
    storagePlanCurrentPro: "Current plan: Pro",
    storagePlanCurrentBadge: "Current",
    storagePlanBasicTitle: "Basic Free",
    storagePlanBasicPrice: "USD $0",
    storagePlanBasicDescription: "Start accounting for free without signing in.",
    storagePlanBasicFeatureLimit: "Up to 200 records stored locally on this device.",
    storagePlanBasicFeatureNoLogin: "No account required.",
    storagePlanPlusTitle: "Plus Local",
    storagePlanPlusPrice: "USD $14.99 one-time",
    storagePlanPlusDescription: "For privacy-first users who want unlimited local records without a subscription.",
    storagePlanPlusFeatureUnlimited: "Unlimited local records.",
    storagePlanPlusFeaturePrivate: "Data stays on this device with no cloud account required.",
    storagePlanProTitle: "Pro Cloud",
    storagePlanProPrice: "{monthly} or {annual}",
    storagePlanProMonthlyFallback: "USD $5.99/month",
    storagePlanProAnnualFallback: "USD $59/year",
    storagePlanProDescription: "For multiple devices, phone changes, couples, families, and shared expenses.",
    storagePlanProFeatureSync: "Unlimited cloud records with automatic sync.",
    storagePlanProFeatureRestore: "Sign in across devices and restore after switching phones.",
    storagePlanProFeatureShared: "Shared books, reimbursements, settlement flow, and separate personal/shared views.",
    storagePlanProFeatureTravel: "Travel accounting.",
    storageUpgradeActionsTitle: "Upgrade when you are ready",
    storageUpgradeProAnnualCta: "Start Pro yearly · {price}",
    storageUpgradeProMonthlyCta: "Start Pro monthly · {price}",
    storageUpgradePlusCta: "Get Plus · {price}",
    storageUpgradePlusComingSoon: "Plus one-time purchase coming soon",
    "features.cloud-backup-sync.title": "Cloud Backup & Sync",
    "features.cloud-backup-sync.message":
      "Optional sign-in to sync across devices and restore data after reinstall.",
    "features.receipt-scan-ocr.title": "Receipt Scan + OCR",
    "features.receipt-scan-ocr.message":
      "Auto-fill amount and merchant information by scanning receipts.",
    "features.export-pdf-spreadsheet.title": "Export to PDF + Spreadsheet Templates",
    "features.export-pdf-spreadsheet.message":
      "Export your data to PDF and use spreadsheet templates for better organization.",
    comingSoon: "Coming Soon",
    dontShowAgain: "Don't Show Again",
    expense: "Expense",
    income: "Income",
    addExpense: "Add Expense",
    addIncome: "Add Income",
    smartLogExpense: "Smart Log Expense",
    smartLogIncome: "Smart Log Income",
    suggestedNames: "Suggested names",
    moneyFlowQuestion: "Where is the money going?",
    timeQuestion: "How am I doing over time?",
    pie: "Pie",
    treemap: "Treemap",
    bar: "Bars",
    line: "Line",
    spendingPie: "Spending Pie",
    spendingTreemap: "Spending Treemap",
    periodCompare: "Period Compare",
    spendingTrend: "Spending Trend",
    topFlow: "Top Flow",
    dailyAverage: "Daily Average",
    groups: "groups",
    noData: "No data",
    errorOccurred: "Something went wrong",
    errorMessage: "We encountered an unexpected error. Please try again or restart the app.",
    tryAgain: "Try Again",
    errorSaveFailed: "Failed to save. Please try again.",
    errorDeleteFailed: "Failed to delete. Please try again.",
    errorLoadFailed: "Failed to load data. Please try again.",
    errorInvalidAmount: "Please enter a valid amount greater than zero.",
    errorAmountTooLarge: "Amount is too large. Maximum is {max}.",
    errorDescriptionTooLong: "Description is too long. Maximum is {max} characters.",
    errorNetworkFailed: "Network error. Please check your connection.",
    errorDatabaseFailed: "Database error. Please restart the app.",
    loading: "Loading...",
    editEntry: "Edit Entry",
    save: "Save",
    saving: "Saving...",
    type: "Type",
    delete: "Delete",
    deleteEntry: "Delete Entry",
    deleteConfirmation: "Are you sure you want to delete this entry?",
    logDate: "Log Date",
  },
  zh: {
    accounting: "記帳",
    statistics: "統計",
    diagram: "圖表",
    total: "總計",
    count: "數量",
    flashAccounting: "黑白記帳",
    noConsumptionsYet: "尚無消費記錄",
    addFirstExpense: "請在上方新增您的第一筆支出",
    amount: "金額",
    description: "描述（選填）",
    noDescription: "無描述",
    add: "新增",
    byDay: "按日",
    byMonth: "按月",
    time: "時間",
    sort: "排序",
    all: "全部",
    today: "今天",
    week: "本週",
    month: "本月",
    year: "今年",
    newest: "最新",
    oldest: "最早",
    highest: "最高",
    lowest: "最低",
    today_label: "今天",
    yesterday: "昨天",
    items: "項",
    item: "項",
    noConsumptions: "未找到消費記錄",
    logDay: "記錄天數",
    rateThisApp: "評分應用",
    settings: "設定",
    exportCSV: "匯出為 CSV",
    selectLanguage: "選擇語言",
    clearHistory: "清除所有歷史",
    clearHistoryConfirm: "確定要清除所有歷史嗎？",
    cancel: "取消",
    confirm: "確認",
    english: "英語",
    chinese: "繁體中文",
    spanish: "西班牙語",
    french: "法語",
    german: "德語",
    japanese: "日語",
    device: "裝置語言",
    exportSuccess: "CSV 匯出成功！",
    exportError: "匯出 CSV 失敗",
    clearSuccess: "歷史記錄已清除",
    exportSharingUnavailable: "此裝置無法使用分享功能",
    errorClearHistoryFailed: "清除歷史記錄失敗",
    authFeatureTitle: "登入功能",
    authFeatureSubtitle: "可選登入，預設本機儲存。",
    authStatusSignedIn: "已登入",
    authStatusSignedOut: "未登入",
    authOptionalNote: "不登入也可以照常使用。",
    authContinueGoogle: "使用 Google 繼續",
    authContinueApple: "使用 Apple 繼續",
    authContinueFacebook: "使用 Facebook 繼續",
    authSignOut: "登出",
    authErrorTitle: "登入失敗",
    authErrorMessage: "請稍後再試一次。",
    authNotConfiguredTitle: "未設定登入",
    authNotConfiguredMessage: "此版本尚未設定 Firebase 登入。",
    cloudSyncTitle: "雲端同步（Pro）",
    cloudSyncActive: "已啟用 — 會儲存到雲端",
    cloudSyncStatusReady: "已就緒 — 裝置與雲端一致",
    cloudSyncStatusSyncing: "同步中",
    cloudSyncStatusPending: "此裝置有待同步的變更",
    cloudSyncStatusError: "同步需要處理",
    cloudSyncLockedSignedIn: "已登入 — 升級即可啟用雲端同步",
    cloudSyncLockedSignedOut: "登入並升級即可啟用雲端同步",
    cloudSyncLockedPaid: "已購買 — 登入後即可使用雲端同步",
    cloudSyncPendingDetail: "本機變更已安全保留。請把此裝置推送到雲端以完成同步。",
    cloudSyncErrorDetail: "目前無法確認雲端同步狀態。請檢查網路或手動重試。",
    cloudSyncLastSynced: "上次成功同步：{date}",
    cloudSyncNeverSynced: "尚未成功完成雲端同步",
    cloudSyncUpgradeCta: "解鎖雲端同步",
    cloudSyncMonthlyCta: "解鎖月繳雲端同步",
    cloudSyncAnnualCta: "解鎖年繳雲端同步",
    cloudSyncRestoreCta: "恢復購買",
    cloudSyncRetryCta: "重試待同步變更",
    cloudSyncRetryDetail: "以此裝置的資料覆蓋雲端，完成待同步變更。",
    cloudSyncSyncCta: "將此裝置推送到雲端",
    cloudSyncSyncDetail: "以此裝置資料覆蓋雲端，然後重新拉取雲端內容。",
    cloudSyncSyncConfirm: "要用此裝置目前的記錄覆蓋雲端資料嗎？",
    cloudSyncSyncDone: "已用 {count} 筆本機記錄覆蓋雲端。",
    cloudSyncSyncFailed: "雲端同步失敗，但本機變更仍安全保留。",
    cloudSyncPullCta: "用雲端資料覆蓋此裝置",
    cloudSyncPullDetail: "放棄待同步的本機變更，下載最新雲端內容。",
    cloudSyncPullConfirm: "要用最新雲端資料覆蓋此裝置記錄嗎？此裝置待同步的本機變更將被捨棄。",
    cloudSyncPullDone: "已下載 {count} 筆雲端記錄到此裝置。",
    cloudSyncPullFailed: "下載雲端資料失敗，目前本機資料已保留。",
    iapNotReadyTitle: "尚未設定購買",
    iapNotReadyMessage: "此版本尚未設定 RevenueCat 購買功能，請加入 API 金鑰並重新建置 App。",
    iapPackageUnavailableMessage: "此方案尚未在目前商店 offering 中上架。",
    iapErrorTitle: "購買失敗",
    iapErrorMessage: "請稍後再試。",
    localLimitTitle: "本機儲存上限",
    localLimitValue: "本機記錄：{count} / {limit}",
    localLimitReachedTitle: "已達上限",
    localLimitReachedMessage:
      "已達免費本機上限。升級 Pro 並登入即可解鎖無上限雲端儲存。",
    localLimitReachedLocalOnlyMessage:
      "此版本已達本機記錄上限。請先刪除部分記錄，再繼續在這台裝置上使用。",
    storageUpgradeTitle: "升級儲存方案",
    storageUpgradeSubtitle: "比較 Basic、Plus、Pro 的儲存選項。",
    storageUpgradeEyebrow: "儲存方案",
    storageUpgradeIntro:
      "依照你的記帳方式選擇方案：免費本機使用、本機無限記錄，或支援多裝置與共用帳本的雲端同步。",
    storagePlanCurrentBasic: "目前方案：Basic",
    storagePlanCurrentPlus: "目前方案：Plus",
    storagePlanCurrentPro: "目前方案：Pro",
    storagePlanCurrentBadge: "目前",
    storagePlanBasicTitle: "Basic 免費",
    storagePlanBasicPrice: "USD $0",
    storagePlanBasicDescription: "免登入即可免費開始記帳，適合先建立記帳習慣。",
    storagePlanBasicFeatureLimit: "本機最多保存 200 筆紀錄。",
    storagePlanBasicFeatureNoLogin: "不需要帳號即可使用。",
    storagePlanPlusTitle: "Plus 單機買斷",
    storagePlanPlusPrice: "USD $14.99 一次性買斷",
    storagePlanPlusDescription: "適合重視隱私、不想訂閱、也不需要雲端同步的使用者。",
    storagePlanPlusFeatureUnlimited: "本機無限記帳。",
    storagePlanPlusFeaturePrivate: "資料完整保存在本機，不需要雲端帳號。",
    storagePlanProTitle: "Pro 雲端與協作",
    storagePlanProPrice: "{monthly} 或 {annual}",
    storagePlanProMonthlyFallback: "USD $5.99/月",
    storagePlanProAnnualFallback: "USD $59/年",
    storagePlanProDescription: "適合多裝置、換機備份、伴侶、夫妻、家庭與共用支出管理。",
    storagePlanProFeatureSync: "雲端無限紀錄與自動同步。",
    storagePlanProFeatureRestore: "跨裝置登入，換手機也能還原資料。",
    storagePlanProFeatureShared: "雙人共用帳本、代墊拆帳、個人與共用視角。",
    storagePlanProFeatureTravel: "旅行記帳。",
    storageUpgradeActionsTitle: "準備好時再升級",
    storageUpgradeProAnnualCta: "啟用 Pro 年繳 · {price}",
    storageUpgradeProMonthlyCta: "啟用 Pro 月繳 · {price}",
    storageUpgradePlusCta: "購買 Plus · {price}",
    storageUpgradePlusComingSoon: "Plus 一次性買斷即將推出",
    "features.cloud-backup-sync.title": "雲端備份與同步",
    "features.cloud-backup-sync.message":
      "可選登入以跨裝置同步，並在重新安裝後還原資料。",
    "features.receipt-scan-ocr.title": "收據掃描 + OCR",
    "features.receipt-scan-ocr.message":
      "掃描收據即可自動填入金額和商家資訊。",
    "features.export-pdf-spreadsheet.title": "匯出至 PDF + 試算表範本",
    "features.export-pdf-spreadsheet.message":
      "將資料匯出為 PDF，並使用試算表範本以更好地組織資料。",
    comingSoon: "即將推出",
    dontShowAgain: "不再顯示",
    expense: "支出",
    income: "收入",
    addExpense: "新增支出",
    addIncome: "新增收入",
    smartLogExpense: "智慧記錄支出",
    smartLogIncome: "智慧記錄收入",
    suggestedNames: "建議名稱",
    moneyFlowQuestion: "錢花到哪裡了？",
    timeQuestion: "這段時間表現如何？",
    pie: "圓餅",
    treemap: "矩形圖",
    bar: "長條",
    line: "折線",
    spendingPie: "支出圓餅圖",
    spendingTreemap: "支出矩形圖",
    periodCompare: "期間比較",
    spendingTrend: "支出趨勢",
    topFlow: "主要流向",
    dailyAverage: "每日平均",
    groups: "類別",
    noData: "無資料",
    errorOccurred: "發生錯誤",
    errorMessage: "我們遇到了意外錯誤。請重試或重新啟動應用程式。",
    tryAgain: "重試",
    errorSaveFailed: "儲存失敗。請重試。",
    errorDeleteFailed: "刪除失敗。請重試。",
    errorLoadFailed: "載入資料失敗。請重試。",
    errorInvalidAmount: "請輸入大於零的有效金額。",
    errorAmountTooLarge: "金額過大。最大值為 {max}。",
    errorDescriptionTooLong: "描述過長。最多 {max} 個字元。",
    errorNetworkFailed: "網路錯誤。請檢查您的連線。",
    errorDatabaseFailed: "資料庫錯誤。請重新啟動應用程式。",
    loading: "載入中...",
    editEntry: "編輯記錄",
    save: "儲存",
    saving: "儲存中...",
    type: "類型",
    delete: "刪除",
    deleteEntry: "刪除記錄",
    deleteConfirmation: "確定要刪除此記錄嗎？",
    logDate: "記錄日期",
  },
  es: {
    accounting: "Contabilidad",
    statistics: "Estadísticas",
    diagram: "Diagrama",
    total: "Total",
    count: "Cantidad",
    flashAccounting: "Contabilidad Blanco Negro",
    noConsumptionsYet: "Aún no hay consumos",
    addFirstExpense: "Agrega tu primer gasto arriba",
    amount: "Cantidad",
    description: "Descripción (opcional)",
    noDescription: "Sin descripción",
    add: "Agregar",
    byDay: "Por Día",
    byMonth: "Por Mes",
    time: "Tiempo",
    sort: "Ordenar",
    all: "Todo",
    today: "Hoy",
    week: "Semana",
    month: "Mes",
    year: "Año",
    newest: "Más reciente",
    oldest: "Más antiguo",
    highest: "Mayor",
    lowest: "Menor",
    today_label: "Hoy",
    yesterday: "Ayer",
    items: "elementos",
    item: "elemento",
    noConsumptions: "No se encontraron consumos",
    logDay: "Días Registrados",
    rateThisApp: "Calificar App",
    settings: "Configuración",
    exportCSV: "Exportar a CSV",
    selectLanguage: "Seleccionar idioma",
    clearHistory: "Borrar todo el historial",
    clearHistoryConfirm:
      "¿Estás seguro de que quieres borrar todo el historial?",
    cancel: "Cancelar",
    confirm: "Confirmar",
    english: "Inglés",
    chinese: "Chino Tradicional",
    spanish: "Español",
    french: "Francés",
    german: "Alemán",
    japanese: "Japonés",
    device: "Idioma del Dispositivo",
    exportSuccess: "¡CSV exportado con éxito!",
    exportError: "Error al exportar CSV",
    clearSuccess: "Historial borrado con éxito",
    exportSharingUnavailable: "Compartir no está disponible en este dispositivo",
    errorClearHistoryFailed: "No se pudo borrar el historial",
    authFeatureTitle: "Inicio de sesión",
    authFeatureSubtitle: "Inicio de sesión opcional. Local por defecto.",
    authStatusSignedIn: "Sesión iniciada",
    authStatusSignedOut: "Sesión no iniciada",
    authOptionalNote: "Puedes seguir usando la app sin iniciar sesión.",
    authContinueGoogle: "Continuar con Google",
    authContinueApple: "Continuar con Apple",
    authContinueFacebook: "Continuar con Facebook",
    authSignOut: "Cerrar sesión",
    authErrorTitle: "Error al iniciar sesión",
    authErrorMessage: "Inténtalo de nuevo.",
    authNotConfiguredTitle: "Inicio de sesión no configurado",
    authNotConfiguredMessage: "Firebase Auth no está configurado en esta versión.",
    cloudSyncTitle: "Sincronización en la nube (Pro)",
    cloudSyncActive: "Activa — guardando en la nube",
    cloudSyncStatusReady: "Listo — dispositivo y nube coinciden",
    cloudSyncStatusSyncing: "Sincronizando",
    cloudSyncStatusPending: "Cambios locales pendientes",
    cloudSyncStatusError: "La sincronización requiere atención",
    cloudSyncLockedSignedIn: "Sesión iniciada — mejora el plan para activar la nube",
    cloudSyncLockedSignedOut: "Inicia sesión y mejora el plan para activar la nube",
    cloudSyncLockedPaid: "Comprado — inicia sesión para usar la nube",
    cloudSyncPendingDetail:
      "Los cambios locales están seguros en este dispositivo. Sube este dispositivo a la nube para terminar la sincronización.",
    cloudSyncErrorDetail:
      "No se pudo comprobar la sincronización en la nube. Revisa tu conexión o reintenta manualmente.",
    cloudSyncLastSynced: "Última sincronización correcta: {date}",
    cloudSyncNeverSynced: "Aún no hay una sincronización en la nube correcta",
    cloudSyncUpgradeCta: "Desbloquear sincronización en la nube",
    cloudSyncMonthlyCta: "Obtener sincronización mensual",
    cloudSyncAnnualCta: "Obtener sincronización anual",
    cloudSyncRestoreCta: "Restaurar compra",
    cloudSyncRetryCta: "Reintentar sincronización pendiente",
    cloudSyncRetryDetail: "Reemplaza los datos en la nube con los de este dispositivo para terminar la sincronización pendiente.",
    cloudSyncSyncCta: "Subir este dispositivo a la nube",
    cloudSyncSyncDetail: "Reemplaza los datos en la nube con los de este dispositivo y luego actualiza desde la nube.",
    cloudSyncSyncConfirm: "¿Reemplazar los datos en la nube con los registros actuales de este dispositivo?",
    cloudSyncSyncDone: "Nube reemplazada con {count} registros locales.",
    cloudSyncSyncFailed: "La sincronización en la nube falló. Tus cambios locales siguen guardados en este dispositivo.",
    cloudSyncPullCta: "Reemplazar este dispositivo desde la nube",
    cloudSyncPullDetail: "Descarta los cambios locales pendientes y descarga la última copia en la nube.",
    cloudSyncPullConfirm:
      "¿Reemplazar los registros de este dispositivo con los datos más recientes de la nube? Se descartarán los cambios locales pendientes.",
    cloudSyncPullDone: "Se descargaron {count} registros de la nube a este dispositivo.",
    cloudSyncPullFailed: "La descarga desde la nube falló. Se conservaron tus datos locales actuales.",
    iapNotReadyTitle: "Compras no configuradas",
    iapNotReadyMessage:
      "Las compras no están configuradas en esta versión. Añade las claves de RevenueCat y vuelve a compilar la app.",
    iapPackageUnavailableMessage: "Este plan no está disponible en la oferta actual de la tienda.",
    iapErrorTitle: "Compra fallida",
    iapErrorMessage: "Inténtalo más tarde.",
    localLimitTitle: "Límite de almacenamiento local",
    localLimitValue: "{count} / {limit} registros en este dispositivo",
    localLimitReachedTitle: "Límite alcanzado",
    localLimitReachedMessage:
      "Alcanzaste el límite local gratuito. Mejora a Pro e inicia sesión para desbloquear almacenamiento ilimitado en la nube.",
    localLimitReachedLocalOnlyMessage:
      "Has alcanzado el limite de registros locales de esta version. Elimina algunos registros para seguir usando este dispositivo.",
    storageUpgradeTitle: "Mejorar plan de almacenamiento",
    storageUpgradeSubtitle: "Compara las opciones Basic, Plus y Pro.",
    storageUpgradeEyebrow: "Almacenamiento",
    storageUpgradeIntro:
      "Elige el plan que se adapte a tu forma de llevar registros: uso local gratuito, almacenamiento local ilimitado o sincronización en la nube para varios dispositivos y libros compartidos.",
    storagePlanCurrentBasic: "Plan actual: Basic",
    storagePlanCurrentPlus: "Plan actual: Plus",
    storagePlanCurrentPro: "Plan actual: Pro",
    storagePlanCurrentBadge: "Actual",
    storagePlanBasicTitle: "Basic gratis",
    storagePlanBasicPrice: "USD $0",
    storagePlanBasicDescription: "Empieza a llevar cuentas gratis sin iniciar sesión.",
    storagePlanBasicFeatureLimit: "Hasta 200 registros guardados localmente en este dispositivo.",
    storagePlanBasicFeatureNoLogin: "No se requiere cuenta.",
    storagePlanPlusTitle: "Plus local",
    storagePlanPlusPrice: "USD $14.99 pago único",
    storagePlanPlusDescription: "Para usuarios que priorizan la privacidad y quieren registros locales ilimitados sin suscripción.",
    storagePlanPlusFeatureUnlimited: "Registros locales ilimitados.",
    storagePlanPlusFeaturePrivate: "Los datos permanecen en este dispositivo sin necesidad de cuenta en la nube.",
    storagePlanProTitle: "Pro nube",
    storagePlanProPrice: "{monthly} o {annual}",
    storagePlanProMonthlyFallback: "USD $5.99/mes",
    storagePlanProAnnualFallback: "USD $59/año",
    storagePlanProDescription: "Para varios dispositivos, cambios de teléfono, parejas, familias y gastos compartidos.",
    storagePlanProFeatureSync: "Registros ilimitados en la nube con sincronización automática.",
    storagePlanProFeatureRestore: "Inicia sesión en varios dispositivos y restaura tras cambiar de teléfono.",
    storagePlanProFeatureShared: "Libros compartidos, reembolsos, liquidaciones y vistas personales/compartidas.",
    storagePlanProFeatureTravel: "Contabilidad de viajes.",
    storageUpgradeActionsTitle: "Mejora cuando estés listo",
    storageUpgradeProAnnualCta: "Activar Pro anual · {price}",
    storageUpgradeProMonthlyCta: "Activar Pro mensual · {price}",
    storageUpgradePlusCta: "Obtener Plus · {price}",
    storageUpgradePlusComingSoon: "Compra única de Plus próximamente",
    "features.cloud-backup-sync.title": "Respaldo en la Nube y Sincronización",
    "features.cloud-backup-sync.message":
      "Inicio de sesión opcional para sincronizar entre dispositivos y restaurar datos después de reinstalar.",
    "features.receipt-scan-ocr.title": "Escaneo de Recibos + OCR",
    "features.receipt-scan-ocr.message":
      "Llena automáticamente el monto y la información del comerciante escaneando recibos.",
    "features.export-pdf-spreadsheet.title": "Exportar a PDF + Plantillas de Hoja de Cálculo",
    "features.export-pdf-spreadsheet.message":
      "Exporta tus datos a PDF y usa plantillas de hoja de cálculo para una mejor organización.",
    comingSoon: "Próximamente",
    dontShowAgain: "No Mostrar de Nuevo",
    expense: "Gasto",
    income: "Ingreso",
    addExpense: "Agregar Gasto",
    addIncome: "Agregar Ingreso",
    smartLogExpense: "Registro inteligente de gastos",
    smartLogIncome: "Registro inteligente de ingresos",
    suggestedNames: "Nombres sugeridos",
    moneyFlowQuestion: "¿A dónde va el dinero?",
    timeQuestion: "¿Cómo voy con el tiempo?",
    pie: "Circular",
    treemap: "Mapa de áreas",
    bar: "Barras",
    line: "Línea",
    spendingPie: "Gráfico circular de gastos",
    spendingTreemap: "Mapa de áreas de gastos",
    periodCompare: "Comparación por periodo",
    spendingTrend: "Tendencia de gastos",
    topFlow: "Mayor flujo",
    dailyAverage: "Promedio diario",
    groups: "grupos",
    noData: "Sin datos",
    errorOccurred: "Algo salió mal",
    errorMessage: "Encontramos un error inesperado. Por favor, inténtalo de nuevo o reinicia la aplicación.",
    tryAgain: "Intentar de Nuevo",
    errorSaveFailed: "Error al guardar. Por favor, inténtalo de nuevo.",
    errorDeleteFailed: "Error al eliminar. Por favor, inténtalo de nuevo.",
    errorLoadFailed: "Error al cargar datos. Por favor, inténtalo de nuevo.",
    errorInvalidAmount: "Por favor, ingresa una cantidad válida mayor que cero.",
    errorAmountTooLarge: "La cantidad es demasiado grande. El máximo es {max}.",
    errorDescriptionTooLong: "La descripción es demasiado larga. El máximo es {max} caracteres.",
    errorNetworkFailed: "Error de red. Por favor, verifica tu conexión.",
    errorDatabaseFailed: "Error de base de datos. Por favor, reinicia la aplicación.",
    loading: "Cargando...",
    editEntry: "Editar entrada",
    save: "Guardar",
    saving: "Guardando...",
    type: "Tipo",
    delete: "Eliminar",
    deleteEntry: "Eliminar entrada",
    deleteConfirmation: "¿Estás seguro de que quieres eliminar esta entrada?",
    logDate: "Fecha del registro",
  },
  fr: {
    accounting: "Comptabilité",
    statistics: "Statistiques",
    diagram: "Graphique",
    total: "Total",
    count: "Nombre",
    flashAccounting: "Comptabilité Blanc Noir",
    noConsumptionsYet: "Aucune consommation pour le moment",
    addFirstExpense: "Ajoutez votre première dépense ci-dessus",
    amount: "Montant",
    description: "Description (optionnel)",
    noDescription: "Aucune description",
    add: "Ajouter",
    byDay: "Par Jour",
    byMonth: "Par Mois",
    time: "Temps",
    sort: "Trier",
    all: "Tout",
    today: "Aujourd'hui",
    week: "Semaine",
    month: "Mois",
    year: "Année",
    newest: "Plus récent",
    oldest: "Plus ancien",
    highest: "Le plus élevé",
    lowest: "Le plus bas",
    today_label: "Aujourd'hui",
    yesterday: "Hier",
    items: "éléments",
    item: "élément",
    noConsumptions: "Aucune consommation trouvée",
    logDay: "Jours d'Enregistrement",
    rateThisApp: "Noter l'App",
    settings: "Paramètres",
    exportCSV: "Exporter en CSV",
    selectLanguage: "Sélectionner la langue",
    clearHistory: "Effacer tout l'historique",
    clearHistoryConfirm: "Êtes-vous sûr de vouloir effacer tout l'historique?",
    cancel: "Annuler",
    confirm: "Confirmer",
    english: "Anglais",
    chinese: "Chinois Traditionnel",
    spanish: "Espagnol",
    french: "Français",
    german: "Allemand",
    japanese: "Japonais",
    device: "Langue de l'Appareil",
    exportSuccess: "CSV exporté avec succès!",
    exportError: "Échec de l'exportation CSV",
    clearSuccess: "Historique effacé avec succès",
    exportSharingUnavailable: "Le partage n'est pas disponible sur cet appareil",
    errorClearHistoryFailed: "Échec de la suppression de l'historique",
    authFeatureTitle: "Connexion",
    authFeatureSubtitle: "Connexion optionnelle. Local par défaut.",
    authStatusSignedIn: "Connecté",
    authStatusSignedOut: "Non connecté",
    authOptionalNote: "Vous pouvez continuer à utiliser l'app sans vous connecter.",
    authContinueGoogle: "Continuer avec Google",
    authContinueApple: "Continuer avec Apple",
    authContinueFacebook: "Continuer avec Facebook",
    authSignOut: "Se déconnecter",
    authErrorTitle: "Échec de la connexion",
    authErrorMessage: "Veuillez réessayer.",
    authNotConfiguredTitle: "Connexion non configurée",
    authNotConfiguredMessage: "Firebase Auth n'est pas configuré pour cette version.",
    cloudSyncTitle: "Synchronisation cloud (Pro)",
    cloudSyncActive: "Active — enregistrement dans le cloud",
    cloudSyncStatusReady: "Prêt — appareil et cloud synchronisés",
    cloudSyncStatusSyncing: "Synchronisation en cours",
    cloudSyncStatusPending: "Modifications locales en attente",
    cloudSyncStatusError: "La synchronisation nécessite une action",
    cloudSyncLockedSignedIn: "Connecté — passez à Pro pour activer le cloud",
    cloudSyncLockedSignedOut: "Connectez-vous et passez à Pro pour activer le cloud",
    cloudSyncLockedPaid: "Acheté — connectez-vous pour utiliser le cloud",
    cloudSyncPendingDetail:
      "Les modifications locales sont en sécurité sur cet appareil. Envoyez cet appareil vers le cloud pour terminer la synchronisation.",
    cloudSyncErrorDetail:
      "Impossible de vérifier la synchronisation cloud. Vérifiez votre connexion ou réessayez manuellement.",
    cloudSyncLastSynced: "Dernière synchronisation réussie : {date}",
    cloudSyncNeverSynced: "Aucune synchronisation cloud réussie pour le moment",
    cloudSyncUpgradeCta: "Débloquer la synchronisation cloud",
    cloudSyncMonthlyCta: "Obtenir la synchronisation mensuelle",
    cloudSyncAnnualCta: "Obtenir la synchronisation annuelle",
    cloudSyncRestoreCta: "Restaurer l'achat",
    cloudSyncRetryCta: "Réessayer la synchronisation en attente",
    cloudSyncRetryDetail: "Remplacez les données cloud par celles de cet appareil pour terminer la synchronisation en attente.",
    cloudSyncSyncCta: "Envoyer cet appareil vers le cloud",
    cloudSyncSyncDetail: "Remplacez les données cloud par celles de cet appareil, puis actualisez depuis le cloud.",
    cloudSyncSyncConfirm: "Remplacer les données cloud par les enregistrements actuels de cet appareil ?",
    cloudSyncSyncDone: "Cloud remplacé par {count} enregistrements locaux.",
    cloudSyncSyncFailed: "La synchronisation cloud a échoué. Vos modifications locales restent enregistrées sur cet appareil.",
    cloudSyncPullCta: "Remplacer cet appareil depuis le cloud",
    cloudSyncPullDetail: "Abandonnez les modifications locales en attente et téléchargez la dernière copie cloud.",
    cloudSyncPullConfirm:
      "Remplacer les enregistrements de cet appareil par les dernières données cloud ? Les modifications locales en attente seront supprimées.",
    cloudSyncPullDone: "{count} enregistrements cloud téléchargés sur cet appareil.",
    cloudSyncPullFailed: "Le téléchargement cloud a échoué. Vos données locales actuelles ont été conservées.",
    iapNotReadyTitle: "Achats non configurés",
    iapNotReadyMessage:
      "Les achats ne sont pas configurés pour cette version. Ajoutez les clés RevenueCat et reconstruisez l'app.",
    iapPackageUnavailableMessage: "Ce forfait n'est pas disponible dans l'offre actuelle du store.",
    iapErrorTitle: "Échec de l'achat",
    iapErrorMessage: "Veuillez réessayer plus tard.",
    localLimitTitle: "Limite de stockage local",
    localLimitValue: "{count} / {limit} enregistrements sur cet appareil",
    localLimitReachedTitle: "Limite atteinte",
    localLimitReachedMessage:
      "Vous avez atteint la limite locale gratuite. Passez à Pro et connectez-vous pour débloquer un stockage cloud illimité.",
    localLimitReachedLocalOnlyMessage:
      "Vous avez atteint la limite d'enregistrements locaux pour cette version. Supprimez quelques entrees pour continuer a utiliser cet appareil.",
    storageUpgradeTitle: "Améliorer le plan de stockage",
    storageUpgradeSubtitle: "Comparez les options Basic, Plus et Pro.",
    storageUpgradeEyebrow: "Stockage",
    storageUpgradeIntro:
      "Choisissez le plan adapté à votre façon de tenir vos comptes : usage local gratuit, stockage local illimité ou synchronisation cloud pour plusieurs appareils et livres partagés.",
    storagePlanCurrentBasic: "Plan actuel : Basic",
    storagePlanCurrentPlus: "Plan actuel : Plus",
    storagePlanCurrentPro: "Plan actuel : Pro",
    storagePlanCurrentBadge: "Actuel",
    storagePlanBasicTitle: "Basic gratuit",
    storagePlanBasicPrice: "USD $0",
    storagePlanBasicDescription: "Commencez la comptabilité gratuitement sans connexion.",
    storagePlanBasicFeatureLimit: "Jusqu'à 200 enregistrements stockés localement sur cet appareil.",
    storagePlanBasicFeatureNoLogin: "Aucun compte requis.",
    storagePlanPlusTitle: "Plus local",
    storagePlanPlusPrice: "USD $14.99 achat unique",
    storagePlanPlusDescription: "Pour les utilisateurs soucieux de la confidentialité qui veulent des enregistrements locaux illimités sans abonnement.",
    storagePlanPlusFeatureUnlimited: "Enregistrements locaux illimités.",
    storagePlanPlusFeaturePrivate: "Les données restent sur cet appareil sans compte cloud requis.",
    storagePlanProTitle: "Pro cloud",
    storagePlanProPrice: "{monthly} ou {annual}",
    storagePlanProMonthlyFallback: "USD $5.99/mois",
    storagePlanProAnnualFallback: "USD $59/an",
    storagePlanProDescription: "Pour plusieurs appareils, changements de téléphone, couples, familles et dépenses partagées.",
    storagePlanProFeatureSync: "Enregistrements cloud illimités avec synchronisation automatique.",
    storagePlanProFeatureRestore: "Connectez-vous sur plusieurs appareils et restaurez après un changement de téléphone.",
    storagePlanProFeatureShared: "Livres partagés, remboursements, règlements et vues personnelles/partagées.",
    storagePlanProFeatureTravel: "Comptabilité de voyage.",
    storageUpgradeActionsTitle: "Améliorez quand vous êtes prêt",
    storageUpgradeProAnnualCta: "Activer Pro annuel · {price}",
    storageUpgradeProMonthlyCta: "Activer Pro mensuel · {price}",
    storageUpgradePlusCta: "Obtenir Plus · {price}",
    storageUpgradePlusComingSoon: "Achat unique Plus bientôt disponible",
    "features.cloud-backup-sync.title": "Sauvegarde Cloud et Synchronisation",
    "features.cloud-backup-sync.message":
      "Connexion optionnelle pour synchroniser entre les appareils et restaurer les données après réinstallation.",
    "features.receipt-scan-ocr.title": "Scan de Reçus + OCR",
    "features.receipt-scan-ocr.message":
      "Remplissage automatique du montant et des informations du commerçant en scannant les reçus.",
    "features.export-pdf-spreadsheet.title": "Exporter vers PDF + Modèles de Tableur",
    "features.export-pdf-spreadsheet.message":
      "Exportez vos données vers PDF et utilisez des modèles de tableur pour une meilleure organisation.",
    comingSoon: "Bientôt Disponible",
    dontShowAgain: "Ne Plus Afficher",
    expense: "Dépense",
    income: "Revenu",
    addExpense: "Ajouter Dépense",
    addIncome: "Ajouter Revenu",
    smartLogExpense: "Saisie intelligente de dépense",
    smartLogIncome: "Saisie intelligente de revenu",
    suggestedNames: "Noms suggérés",
    moneyFlowQuestion: "Où va l'argent ?",
    timeQuestion: "Comment je m'en sors dans le temps ?",
    pie: "Camembert",
    treemap: "Treemap",
    bar: "Barres",
    line: "Courbe",
    spendingPie: "Camembert des dépenses",
    spendingTreemap: "Treemap des dépenses",
    periodCompare: "Comparaison par période",
    spendingTrend: "Tendance des dépenses",
    topFlow: "Flux principal",
    dailyAverage: "Moyenne quotidienne",
    groups: "groupes",
    noData: "Aucune donnée",
    errorOccurred: "Une erreur s'est produite",
    errorMessage: "Nous avons rencontré une erreur inattendue. Veuillez réessayer ou redémarrer l'application.",
    tryAgain: "Réessayer",
    errorSaveFailed: "Échec de l'enregistrement. Veuillez réessayer.",
    errorDeleteFailed: "Échec de la suppression. Veuillez réessayer.",
    errorLoadFailed: "Échec du chargement des données. Veuillez réessayer.",
    errorInvalidAmount: "Veuillez entrer un montant valide supérieur à zéro.",
    errorAmountTooLarge: "Le montant est trop élevé. Le maximum est {max}.",
    errorDescriptionTooLong: "La description est trop longue. Le maximum est {max} caractères.",
    errorNetworkFailed: "Erreur réseau. Veuillez vérifier votre connexion.",
    errorDatabaseFailed: "Erreur de base de données. Veuillez redémarrer l'application.",
    loading: "Chargement...",
    editEntry: "Modifier l'entrée",
    save: "Enregistrer",
    saving: "Enregistrement...",
    type: "Type",
    delete: "Supprimer",
    deleteEntry: "Supprimer l'entrée",
    deleteConfirmation: "Êtes-vous sûr de vouloir supprimer cette entrée?",
    logDate: "Date du journal",
  },
  de: {
    accounting: "Buchhaltung",
    statistics: "Statistiken",
    diagram: "Diagramm",
    total: "Gesamt",
    count: "Anzahl",
    flashAccounting: "Schwarz Weiß Buchhaltung",
    noConsumptionsYet: "Noch keine Verbräuche",
    addFirstExpense: "Fügen Sie oben Ihre erste Ausgabe hinzu",
    amount: "Betrag",
    description: "Beschreibung (optional)",
    noDescription: "Keine Beschreibung",
    add: "Hinzufügen",
    byDay: "Nach Tag",
    byMonth: "Nach Monat",
    time: "Zeit",
    sort: "Sortieren",
    all: "Alle",
    today: "Heute",
    week: "Woche",
    month: "Monat",
    year: "Jahr",
    newest: "Neueste",
    oldest: "Älteste",
    highest: "Höchste",
    lowest: "Niedrigste",
    today_label: "Heute",
    yesterday: "Gestern",
    items: "Elemente",
    item: "Element",
    noConsumptions: "Keine Verbräuche gefunden",
    logDay: "Registriertage",
    rateThisApp: "App Bewerten",
    settings: "Einstellungen",
    exportCSV: "Als CSV exportieren",
    selectLanguage: "Sprache auswählen",
    clearHistory: "Gesamten Verlauf löschen",
    clearHistoryConfirm:
      "Sind Sie sicher, dass Sie den gesamten Verlauf löschen möchten?",
    cancel: "Abbrechen",
    confirm: "Bestätigen",
    english: "Englisch",
    chinese: "Traditionelles Chinesisch",
    spanish: "Spanisch",
    french: "Französisch",
    german: "Deutsch",
    japanese: "Japanisch",
    device: "Gerätesprache",
    exportSuccess: "CSV erfolgreich exportiert!",
    exportError: "CSV-Export fehlgeschlagen",
    clearSuccess: "Verlauf erfolgreich gelöscht",
    exportSharingUnavailable: "Teilen ist auf diesem Gerät nicht verfügbar",
    errorClearHistoryFailed: "Verlauf konnte nicht gelöscht werden",
    authFeatureTitle: "Anmeldung",
    authFeatureSubtitle: "Optionale Anmeldung. Standardmäßig lokal.",
    authStatusSignedIn: "Angemeldet",
    authStatusSignedOut: "Nicht angemeldet",
    authOptionalNote: "Du kannst die App auch ohne Anmeldung weiter nutzen.",
    authContinueGoogle: "Mit Google fortfahren",
    authContinueApple: "Mit Apple fortfahren",
    authContinueFacebook: "Mit Facebook fortfahren",
    authSignOut: "Abmelden",
    authErrorTitle: "Anmeldung fehlgeschlagen",
    authErrorMessage: "Bitte versuche es erneut.",
    authNotConfiguredTitle: "Anmeldung nicht konfiguriert",
    authNotConfiguredMessage: "Firebase Auth ist für diese Version nicht konfiguriert.",
    cloudSyncTitle: "Cloud-Synchronisation (Pro)",
    cloudSyncActive: "Aktiv — speichert in der Cloud",
    cloudSyncStatusReady: "Bereit — Gerät und Cloud stimmen überein",
    cloudSyncStatusSyncing: "Synchronisiert",
    cloudSyncStatusPending: "Ausstehende lokale Änderungen",
    cloudSyncStatusError: "Synchronisation erfordert Aufmerksamkeit",
    cloudSyncLockedSignedIn: "Angemeldet — Upgrade für Cloud-Sync erforderlich",
    cloudSyncLockedSignedOut: "Anmelden und upgraden, um Cloud-Sync zu aktivieren",
    cloudSyncLockedPaid: "Gekauft — anmelden, um Cloud-Sync zu nutzen",
    cloudSyncPendingDetail:
      "Lokale Änderungen sind auf diesem Gerät sicher. Lade dieses Gerät in die Cloud hoch, um die Synchronisation abzuschließen.",
    cloudSyncErrorDetail:
      "Cloud-Synchronisation konnte nicht geprüft werden. Überprüfe deine Verbindung oder versuche es manuell erneut.",
    cloudSyncLastSynced: "Letzte erfolgreiche Synchronisation: {date}",
    cloudSyncNeverSynced: "Noch keine erfolgreiche Cloud-Synchronisation",
    cloudSyncUpgradeCta: "Cloud-Sync freischalten",
    cloudSyncMonthlyCta: "Monatlichen Cloud-Sync erhalten",
    cloudSyncAnnualCta: "Jährlichen Cloud-Sync erhalten",
    cloudSyncRestoreCta: "Kauf wiederherstellen",
    cloudSyncRetryCta: "Ausstehende Synchronisation wiederholen",
    cloudSyncRetryDetail: "Ersetze Cloud-Daten durch dieses Gerät, um die ausstehende Synchronisation abzuschließen.",
    cloudSyncSyncCta: "Dieses Gerät in die Cloud hochladen",
    cloudSyncSyncDetail: "Ersetze Cloud-Daten durch dieses Gerät und aktualisiere anschließend aus der Cloud.",
    cloudSyncSyncConfirm: "Cloud-Daten durch die aktuellen Einträge auf diesem Gerät ersetzen?",
    cloudSyncSyncDone: "Cloud durch {count} lokale Einträge ersetzt.",
    cloudSyncSyncFailed: "Cloud-Synchronisation fehlgeschlagen. Deine lokalen Änderungen sind weiterhin auf diesem Gerät gespeichert.",
    cloudSyncPullCta: "Dieses Gerät aus der Cloud ersetzen",
    cloudSyncPullDetail: "Verwirf ausstehende lokale Änderungen und lade die neueste Cloud-Kopie herunter.",
    cloudSyncPullConfirm:
      "Einträge auf diesem Gerät durch die neuesten Cloud-Daten ersetzen? Ausstehende lokale Änderungen werden verworfen.",
    cloudSyncPullDone: "{count} Cloud-Einträge auf dieses Gerät heruntergeladen.",
    cloudSyncPullFailed: "Cloud-Download fehlgeschlagen. Deine aktuellen lokalen Daten wurden behalten.",
    iapNotReadyTitle: "Käufe nicht eingerichtet",
    iapNotReadyMessage:
      "Käufe sind für diese Version nicht konfiguriert. Füge RevenueCat-Schlüssel hinzu und baue die App neu.",
    iapPackageUnavailableMessage: "Dieses Paket ist im aktuellen Store-Angebot nicht verfügbar.",
    iapErrorTitle: "Kauf fehlgeschlagen",
    iapErrorMessage: "Bitte versuche es später erneut.",
    localLimitTitle: "Lokales Speicherlimit",
    localLimitValue: "{count} / {limit} Einträge auf diesem Gerät",
    localLimitReachedTitle: "Limit erreicht",
    localLimitReachedMessage:
      "Du hast das kostenlose lokale Limit erreicht. Upgrade auf Pro und melde dich an, um unbegrenzten Cloud-Speicher freizuschalten.",
    localLimitReachedLocalOnlyMessage:
      "Sie haben das lokale Datensatzlimit fur diese Version erreicht. Loschen Sie einige Eintrage, um dieses Gerat weiter zu verwenden.",
    storageUpgradeTitle: "Speicherplan upgraden",
    storageUpgradeSubtitle: "Vergleiche Basic-, Plus- und Pro-Optionen.",
    storageUpgradeEyebrow: "Speicher",
    storageUpgradeIntro:
      "Wähle den Plan, der zu deiner Art passt, Einträge zu führen: kostenlose lokale Nutzung, unbegrenzter lokaler Speicher oder Cloud-Sync für mehrere Geräte und gemeinsame Bücher.",
    storagePlanCurrentBasic: "Aktueller Plan: Basic",
    storagePlanCurrentPlus: "Aktueller Plan: Plus",
    storagePlanCurrentPro: "Aktueller Plan: Pro",
    storagePlanCurrentBadge: "Aktuell",
    storagePlanBasicTitle: "Basic kostenlos",
    storagePlanBasicPrice: "USD $0",
    storagePlanBasicDescription: "Starte kostenlos mit der Buchhaltung ohne Anmeldung.",
    storagePlanBasicFeatureLimit: "Bis zu 200 Einträge lokal auf diesem Gerät gespeichert.",
    storagePlanBasicFeatureNoLogin: "Kein Konto erforderlich.",
    storagePlanPlusTitle: "Plus lokal",
    storagePlanPlusPrice: "USD $14.99 einmalig",
    storagePlanPlusDescription: "Für datenschutzbewusste Nutzer, die unbegrenzte lokale Einträge ohne Abo wollen.",
    storagePlanPlusFeatureUnlimited: "Unbegrenzte lokale Einträge.",
    storagePlanPlusFeaturePrivate: "Daten bleiben auf diesem Gerät, kein Cloud-Konto erforderlich.",
    storagePlanProTitle: "Pro Cloud",
    storagePlanProPrice: "{monthly} oder {annual}",
    storagePlanProMonthlyFallback: "USD $5.99/Monat",
    storagePlanProAnnualFallback: "USD $59/Jahr",
    storagePlanProDescription: "Für mehrere Geräte, Telefonwechsel, Paare, Familien und gemeinsame Ausgaben.",
    storagePlanProFeatureSync: "Unbegrenzte Cloud-Einträge mit automatischer Synchronisation.",
    storagePlanProFeatureRestore: "Melde dich auf mehreren Geräten an und stelle nach einem Telefonwechsel wieder her.",
    storagePlanProFeatureShared: "Gemeinsame Bücher, Erstattungen, Abrechnungen und getrennte persönliche/gemeinsame Ansichten.",
    storagePlanProFeatureTravel: "Reisebuchhaltung.",
    storageUpgradeActionsTitle: "Upgrade, wenn du bereit bist",
    storageUpgradeProAnnualCta: "Pro jährlich starten · {price}",
    storageUpgradeProMonthlyCta: "Pro monatlich starten · {price}",
    storageUpgradePlusCta: "Plus erhalten · {price}",
    storageUpgradePlusComingSoon: "Plus-Einmalkauf demnächst verfügbar",
    "features.cloud-backup-sync.title": "Cloud-Backup & Synchronisation",
    "features.cloud-backup-sync.message":
      "Optionaler Anmeldung zur Synchronisation zwischen Geräten und Wiederherstellung von Daten nach Neuinstallation.",
    "features.receipt-scan-ocr.title": "Beleg-Scan + OCR",
    "features.receipt-scan-ocr.message":
      "Automatisches Ausfüllen von Betrag und Händlerinformationen durch Scannen von Belegen.",
    "features.export-pdf-spreadsheet.title": "Export nach PDF + Tabellenkalkulationsvorlagen",
    "features.export-pdf-spreadsheet.message":
      "Exportieren Sie Ihre Daten nach PDF und verwenden Sie Tabellenkalkulationsvorlagen für bessere Organisation.",
    comingSoon: "Demnächst",
    dontShowAgain: "Nicht Mehr Anzeigen",
    expense: "Ausgabe",
    income: "Einnahme",
    addExpense: "Ausgabe Hinzufügen",
    addIncome: "Einnahme Hinzufügen",
    smartLogExpense: "Intelligente Ausgabe erfassen",
    smartLogIncome: "Intelligente Einnahme erfassen",
    suggestedNames: "Vorgeschlagene Namen",
    moneyFlowQuestion: "Wohin fließt das Geld?",
    timeQuestion: "Wie entwickle ich mich über die Zeit?",
    pie: "Kreis",
    treemap: "Treemap",
    bar: "Balken",
    line: "Linie",
    spendingPie: "Ausgaben-Kreisdiagramm",
    spendingTreemap: "Ausgaben-Treemap",
    periodCompare: "Periodenvergleich",
    spendingTrend: "Ausgabentrend",
    topFlow: "Top-Kategorie",
    dailyAverage: "Tagesdurchschnitt",
    groups: "Gruppen",
    noData: "Keine Daten",
    errorOccurred: "Ein Fehler ist aufgetreten",
    errorMessage: "Wir haben einen unerwarteten Fehler festgestellt. Bitte versuchen Sie es erneut oder starten Sie die App neu.",
    tryAgain: "Erneut Versuchen",
    errorSaveFailed: "Speichern fehlgeschlagen. Bitte versuchen Sie es erneut.",
    errorDeleteFailed: "Löschen fehlgeschlagen. Bitte versuchen Sie es erneut.",
    errorLoadFailed: "Daten laden fehlgeschlagen. Bitte versuchen Sie es erneut.",
    errorInvalidAmount: "Bitte geben Sie einen gültigen Betrag größer als null ein.",
    errorAmountTooLarge: "Der Betrag ist zu groß. Das Maximum ist {max}.",
    errorDescriptionTooLong: "Die Beschreibung ist zu lang. Das Maximum ist {max} Zeichen.",
    errorNetworkFailed: "Netzwerkfehler. Bitte überprüfen Sie Ihre Verbindung.",
    errorDatabaseFailed: "Datenbankfehler. Bitte starten Sie die App neu.",
    loading: "Laden...",
    editEntry: "Eintrag bearbeiten",
    save: "Speichern",
    saving: "Speichern...",
    type: "Typ",
    delete: "Löschen",
    deleteEntry: "Eintrag löschen",
    deleteConfirmation: "Sind Sie sicher, dass Sie diesen Eintrag löschen möchten?",
    logDate: "Buchungsdatum",
  },
  ja: {
    accounting: "会計",
    statistics: "統計",
    diagram: "グラフ",
    total: "合計",
    count: "件数",
    flashAccounting: "白黒会計",
    noConsumptionsYet: "消費がまだありません",
    addFirstExpense: "上記に最初の支出を追加してください",
    amount: "金額",
    description: "説明（任意）",
    noDescription: "説明なし",
    add: "追加",
    byDay: "日別",
    byMonth: "月別",
    time: "時間",
    sort: "並び替え",
    all: "全て",
    today: "今日",
    week: "今週",
    month: "今月",
    year: "今年",
    newest: "最新",
    oldest: "最古",
    highest: "最高",
    lowest: "最低",
    today_label: "今日",
    yesterday: "昨日",
    items: "件",
    item: "件",
    noConsumptions: "消費が見つかりません",
    logDay: "記録日数",
    rateThisApp: "アプリを評価",
    settings: "設定",
    exportCSV: "CSVにエクスポート",
    selectLanguage: "言語を選択",
    clearHistory: "履歴をすべてクリア",
    clearHistoryConfirm: "すべての履歴をクリアしてもよろしいですか？",
    cancel: "キャンセル",
    confirm: "確認",
    english: "英語",
    chinese: "繁体中国語",
    spanish: "スペイン語",
    french: "フランス語",
    german: "ドイツ語",
    japanese: "日本語",
    device: "デバイス言語",
    exportSuccess: "CSVのエクスポートに成功しました！",
    exportError: "CSVのエクスポートに失敗しました",
    clearSuccess: "履歴がクリアされました",
    exportSharingUnavailable: "このデバイスでは共有機能を利用できません",
    errorClearHistoryFailed: "履歴のクリアに失敗しました",
    authFeatureTitle: "ログイン",
    authFeatureSubtitle: "任意のログイン。デフォルトはローカル保存。",
    authStatusSignedIn: "ログイン済み",
    authStatusSignedOut: "未ログイン",
    authOptionalNote: "ログインしなくてもアプリを使い続けられます。",
    authContinueGoogle: "Google で続行",
    authContinueApple: "Apple で続行",
    authContinueFacebook: "Facebook で続行",
    authSignOut: "ログアウト",
    authErrorTitle: "ログインに失敗しました",
    authErrorMessage: "もう一度お試しください。",
    authNotConfiguredTitle: "ログインが設定されていません",
    authNotConfiguredMessage: "このビルドでは Firebase 認証が設定されていません。",
    cloudSyncTitle: "クラウド同期（Pro）",
    cloudSyncActive: "有効 — クラウドに保存中",
    cloudSyncStatusReady: "準備完了 — デバイスとクラウドが一致",
    cloudSyncStatusSyncing: "同期中",
    cloudSyncStatusPending: "保留中のローカル変更あり",
    cloudSyncStatusError: "同期に対応が必要です",
    cloudSyncLockedSignedIn: "ログイン済み — アップグレードでクラウド同期を有効化",
    cloudSyncLockedSignedOut: "ログインとアップグレードでクラウド同期を有効化",
    cloudSyncLockedPaid: "購入済み — ログインしてクラウド同期を利用",
    cloudSyncPendingDetail:
      "ローカル変更はこのデバイスに安全に保存されています。このデバイスをクラウドに送信して同期を完了してください。",
    cloudSyncErrorDetail:
      "クラウド同期を確認できませんでした。接続を確認するか、手動で再試行してください。",
    cloudSyncLastSynced: "最後の同期成功: {date}",
    cloudSyncNeverSynced: "まだクラウド同期に成功していません",
    cloudSyncUpgradeCta: "クラウド同期を解除",
    cloudSyncMonthlyCta: "月額クラウド同期を取得",
    cloudSyncAnnualCta: "年額クラウド同期を取得",
    cloudSyncRestoreCta: "購入を復元",
    cloudSyncRetryCta: "保留中の同期を再試行",
    cloudSyncRetryDetail: "保留中の同期を完了するため、このデバイスのデータでクラウドを置き換えます。",
    cloudSyncSyncCta: "このデバイスをクラウドに送信",
    cloudSyncSyncDetail: "このデバイスのデータでクラウドを置き換え、その後クラウドから更新します。",
    cloudSyncSyncConfirm: "このデバイスの現在の記録でクラウドデータを置き換えますか？",
    cloudSyncSyncDone: "クラウドを {count} 件のローカル記録で置き換えました。",
    cloudSyncSyncFailed: "クラウド同期に失敗しました。ローカル変更はこのデバイスに保存されています。",
    cloudSyncPullCta: "このデバイスをクラウドで置き換え",
    cloudSyncPullDetail: "保留中のローカル変更を破棄し、最新のクラウドコピーをダウンロードします。",
    cloudSyncPullConfirm:
      "このデバイスの記録を最新のクラウドデータで置き換えますか？保留中のローカル変更は破棄されます。",
    cloudSyncPullDone: "クラウドから {count} 件の記録をこのデバイスにダウンロードしました。",
    cloudSyncPullFailed: "クラウドのダウンロードに失敗しました。現在のローカルデータは保持されています。",
    iapNotReadyTitle: "購入が設定されていません",
    iapNotReadyMessage:
      "このビルドでは購入が設定されていません。RevenueCat キーを追加してアプリを再ビルドしてください。",
    iapPackageUnavailableMessage: "このプランは現在のストア offering では利用できません。",
    iapErrorTitle: "購入に失敗しました",
    iapErrorMessage: "後でもう一度お試しください。",
    localLimitTitle: "ローカル保存上限",
    localLimitValue: "このデバイスの記録: {count} / {limit}",
    localLimitReachedTitle: "上限に達しました",
    localLimitReachedMessage:
      "無料のローカル上限に達しました。Pro にアップグレードしてログインすると、無制限のクラウド保存が利用できます。",
    localLimitReachedLocalOnlyMessage:
      "このビルドのローカル記録上限に達しました。このデバイスで使い続けるには、いくつかの記録を削除してください。",
    storageUpgradeTitle: "保存プランをアップグレード",
    storageUpgradeSubtitle: "Basic、Plus、Pro の保存オプションを比較。",
    storageUpgradeEyebrow: "保存プラン",
    storageUpgradeIntro:
      "記録の使い方に合わせてプランを選びましょう: 無料ローカル利用、無制限ローカル保存、または複数デバイスと共有帳簿向けのクラウド同期。",
    storagePlanCurrentBasic: "現在のプラン: Basic",
    storagePlanCurrentPlus: "現在のプラン: Plus",
    storagePlanCurrentPro: "現在のプラン: Pro",
    storagePlanCurrentBadge: "現在",
    storagePlanBasicTitle: "Basic 無料",
    storagePlanBasicPrice: "USD $0",
    storagePlanBasicDescription: "ログインなしで無料で家計簿を始められます。",
    storagePlanBasicFeatureLimit: "このデバイスに最大 200 件までローカル保存。",
    storagePlanBasicFeatureNoLogin: "アカウント不要。",
    storagePlanPlusTitle: "Plus ローカル",
    storagePlanPlusPrice: "USD $14.99 買い切り",
    storagePlanPlusDescription: "プライバシー重視で、サブスクなしの無制限ローカル記録を求めるユーザー向け。",
    storagePlanPlusFeatureUnlimited: "ローカル記録無制限。",
    storagePlanPlusFeaturePrivate: "データはこのデバイスに保存され、クラウドアカウントは不要。",
    storagePlanProTitle: "Pro クラウド",
    storagePlanProPrice: "{monthly} または {annual}",
    storagePlanProMonthlyFallback: "USD $5.99/月",
    storagePlanProAnnualFallback: "USD $59/年",
    storagePlanProDescription: "複数デバイス、機種変更、カップル、家族、共有支出向け。",
    storagePlanProFeatureSync: "無制限クラウド記録と自動同期。",
    storagePlanProFeatureRestore: "複数デバイスでログインし、機種変更後も復元可能。",
    storagePlanProFeatureShared: "共有帳簿、立て替え精算、個人/共有ビュー。",
    storagePlanProFeatureTravel: "旅行記帳。",
    storageUpgradeActionsTitle: "準備ができたらアップグレード",
    storageUpgradeProAnnualCta: "Pro 年額を開始 · {price}",
    storageUpgradeProMonthlyCta: "Pro 月額を開始 · {price}",
    storageUpgradePlusCta: "Plus を取得 · {price}",
    storageUpgradePlusComingSoon: "Plus 買い切りは近日公開",
    "features.cloud-backup-sync.title": "クラウドバックアップと同期",
    "features.cloud-backup-sync.message":
      "オプションのサインインでデバイス間で同期し、再インストール後にデータを復元できます。",
    "features.receipt-scan-ocr.title": "レシートスキャン + OCR",
    "features.receipt-scan-ocr.message":
      "レシートをスキャンして金額と店舗情報を自動入力します。",
    "features.export-pdf-spreadsheet.title": "PDF + スプレッドシートテンプレートへのエクスポート",
    "features.export-pdf-spreadsheet.message":
      "データをPDFにエクスポートし、スプレッドシートテンプレートを使用してより良い整理ができます。",
    comingSoon: "近日公開",
    dontShowAgain: "今後表示しない",
    expense: "支出",
    income: "収入",
    addExpense: "支出を追加",
    addIncome: "収入を追加",
    smartLogExpense: "スマート支出記録",
    smartLogIncome: "スマート収入記録",
    suggestedNames: "候補名",
    moneyFlowQuestion: "お金はどこに使われていますか？",
    timeQuestion: "この期間の推移はどうですか？",
    pie: "円グラフ",
    treemap: "ツリーマップ",
    bar: "棒グラフ",
    line: "折れ線",
    spendingPie: "支出円グラフ",
    spendingTreemap: "支出ツリーマップ",
    periodCompare: "期間比較",
    spendingTrend: "支出推移",
    topFlow: "最大項目",
    dailyAverage: "1日平均",
    groups: "分類",
    noData: "データなし",
    errorOccurred: "エラーが発生しました",
    errorMessage: "予期しないエラーが発生しました。もう一度お試しいただくか、アプリを再起動してください。",
    tryAgain: "再試行",
    errorSaveFailed: "保存に失敗しました。もう一度お試しください。",
    errorDeleteFailed: "削除に失敗しました。もう一度お試しください。",
    errorLoadFailed: "データの読み込みに失敗しました。もう一度お試しください。",
    errorInvalidAmount: "ゼロより大きい有効な金額を入力してください。",
    errorAmountTooLarge: "金額が大きすぎます。最大値は {max} です。",
    errorDescriptionTooLong: "説明が長すぎます。最大 {max} 文字です。",
    errorNetworkFailed: "ネットワークエラー。接続を確認してください。",
    errorDatabaseFailed: "データベースエラー。アプリを再起動してください。",
    loading: "読み込み中...",
    editEntry: "編集",
    save: "保存",
    saving: "保存中...",
    type: "種類",
    delete: "削除",
    deleteEntry: "削除",
    deleteConfirmation: "このエントリを削除してもよろしいですか？",
    logDate: "記録日",
  },
};

const GLOSSARY_TRANSLATIONS: Record<ResolvedLanguage, Record<string, string>> = {
  en: GLOSSARY_TRANSLATION_EN,
  zh: GLOSSARY_TRANSLATION_ZH,
  es: GLOSSARY_TRANSLATION_ES,
  fr: GLOSSARY_TRANSLATION_FR,
  de: GLOSSARY_TRANSLATION_DE,
  ja: GLOSSARY_TRANSLATION_JA,
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("device");

  // Get the resolved language (actual language code used for translations)
  // Memoize to avoid recalculating device language on every render
  const resolvedLanguage: ResolvedLanguage = useMemo(() => {
    return language === "device" ? getDeviceLanguage() : language;
  }, [language]);

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const saved = await AsyncStorage.getItem(STORAGE_KEYS.LANGUAGE);
      if (saved && SUPPORTED_LANGUAGES.includes(saved as Language)) {
        setLanguageState(saved as Language);
      } else {
        setLanguageState("device");
      }
    } catch (error) {
      logger.error("Failed to load language", error);
      setLanguageState("device");
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem(STORAGE_KEYS.LANGUAGE, lang);
      setLanguageState(lang);
    } catch (error) {
      logger.error("Failed to save language", error);
    }
  };

  const t = useMemo(
    () =>
      (key: string): string => {
        return (
          translations[resolvedLanguage]?.[key] ||
          GLOSSARY_TRANSLATIONS[resolvedLanguage]?.[key] ||
          translations.en[key] ||
          GLOSSARY_TRANSLATIONS.en[key] ||
          key
        );
      },
    [resolvedLanguage]
  );

  const contextValue = useMemo(
    () => ({ language, resolvedLanguage, setLanguage, t }),
    [language, resolvedLanguage, t],
  );

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
