import { STORAGE_KEYS, SUPPORTED_LANGUAGES } from "@/utils/constants";
import type { ResolvedLanguage } from "@/utils/formatting";
import {
  GLOSSARY_TRANSLATION_DE,
  GLOSSARY_TRANSLATION_EN,
  GLOSSARY_TRANSLATION_ES,
  GLOSSARY_TRANSLATION_FR,
  GLOSSARY_TRANSLATION_JA,
  GLOSSARY_TRANSLATION_ZH,
} from "@/utils/glossary-i18n";
import { logger } from "@/utils/logger";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Localization from "expo-localization";
import React, {
    createContext,
    useContext,
    useEffect,
    useMemo,
    useState,
} from "react";

export type Language = "en" | "zh" | "es" | "fr" | "de" | "ja" | "device";

export interface LanguageContextType {
  language: Language;
  resolvedLanguage: ResolvedLanguage;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
}

// Detect device locale and map to supported languages
const getDeviceLanguage = (): ResolvedLanguage => {
  try {
    // Get the device locales from expo-localization
    const locales = Localization.getLocales();

    // Ensure locales is an array and has at least one element
    if (!Array.isArray(locales) || locales.length === 0) {
      logger.warn("No device locales found, falling back to English");
      return "en";
    }

    // Use the first locale (primary device language)
    const primaryLocale = locales[0];
    if (!primaryLocale) {
      logger.warn("Primary locale is undefined, falling back to English");
      return "en";
    }

    // Extract language code (e.g., "en" from "en-US")
    let langCode: string | null = null;

    // Try languageCode first (most reliable)
    if (primaryLocale.languageCode) {
      langCode = primaryLocale.languageCode.toLowerCase();
    }
    // Fallback to extracting from languageTag (e.g., "en-US" -> "en")
    else if (primaryLocale.languageTag) {
      const parts = primaryLocale.languageTag.split("-");
      if (parts.length > 0) {
        langCode = parts[0].toLowerCase();
      }
    }

    // If we still don't have a language code, fall back to English
    if (!langCode) {
      logger.warn(
        "Could not extract language code from locale, falling back to English",
        { locale: primaryLocale }
      );
      return "en";
    }

    // Map device language codes to our supported languages
    // Fallback to "en" if the device language is not supported
    const languageMap: Record<string, ResolvedLanguage> = {
      en: "en",
      zh: "zh", // Supports both zh-Hans and zh-Hant
      es: "es",
      fr: "fr",
      de: "de",
      ja: "ja",
    };

    const resolvedLang = languageMap[langCode];
    if (!resolvedLang) {
      logger.debug(
        "Device language is not supported, falling back to English",
        { langCode }
      );
      return "en";
    }

    return resolvedLang;
  } catch (error) {
    logger.error("Failed to detect device language", error);
    // Always fall back to English on any error
    return "en";
  }
};

const translations: Record<ResolvedLanguage, Record<string, string>> = {
  en: {
    accounting: "Accounting",
    statistics: "Statistics",
    diagram: "Diagram",
    total: "Total",
    count: "Count",
    flashAccounting: "Black White Accounting",
    noConsumptionsYet: "No consumptions yet",
    addFirstExpense: "Add your first expense above",
    amount: "Amount",
    description: "Description (optional)",
    noDescription: "No description",
    add: "Add",
    byDay: "By Day",
    byMonth: "By Month",
    time: "Time",
    sort: "Sort",
    all: "All",
    today: "Today",
    week: "Week",
    month: "Month",
    year: "Year",
    newest: "Newest",
    oldest: "Oldest",
    highest: "Highest",
    lowest: "Lowest",
    today_label: "Today",
    yesterday: "Yesterday",
    items: "items",
    item: "item",
    noConsumptions: "No consumptions found",
    logDay: "Log Day",
    rateThisApp: "Rate This App",
    settings: "Settings",
    exportCSV: "Export to CSV",
    selectLanguage: "Select Language",
    clearHistory: "Clear All History",
    clearHistoryConfirm: "Are you sure you want to clear all history?",
    cancel: "Cancel",
    confirm: "Confirm",
    english: "English",
    chinese: "Traditional Chinese",
    spanish: "Spanish",
    french: "French",
    german: "German",
    japanese: "Japanese",
    device: "Device Language",
    exportSuccess: "CSV exported successfully!",
    exportError: "Failed to export CSV",
    clearSuccess: "History cleared successfully",
    authFeatureTitle: "Auth feature",
    authFeatureSubtitle: "Optional sign-in. Local-first by default.",
    authStatusSignedIn: "Signed in",
    authStatusSignedOut: "Not signed in",
    authOptionalNote: "You can keep using the app without signing in.",
    authContinueGoogle: "Continue with Google",
    authContinueApple: "Continue with Apple",
    authContinueFacebook: "Continue with Facebook",
    authSignOut: "Sign out",
    authErrorTitle: "Sign-in failed",
    authErrorMessage: "Please try again.",
    authNotConfiguredTitle: "Auth not configured",
    authNotConfiguredMessage: "Firebase auth is not configured for this build.",
    cloudSyncTitle: "Cloud Sync (Pro)",
    cloudSyncActive: "Active — saving to cloud",
    cloudSyncStatusReady: "Ready — device and cloud match",
    cloudSyncStatusSyncing: "Syncing now",
    cloudSyncStatusPending: "Pending local changes",
    cloudSyncStatusError: "Sync needs attention",
    cloudSyncLockedSignedIn: "Signed in — upgrade to enable cloud sync",
    cloudSyncLockedSignedOut: "Sign in + upgrade to enable cloud sync",
    cloudSyncLockedPaid: "Purchased — sign in to use cloud sync",
    cloudSyncPendingDetail:
      "Local changes are safe on this device. Push this device to cloud to finish syncing.",
    cloudSyncErrorDetail:
      "Cloud sync could not be checked. Review your connection or retry manually.",
    cloudSyncLastSynced: "Last successful sync: {date}",
    cloudSyncNeverSynced: "No successful cloud sync yet",
    cloudSyncUpgradeCta: "Unlock Cloud Sync",
    cloudSyncMonthlyCta: "Get Monthly Cloud Sync",
    cloudSyncAnnualCta: "Get Yearly Cloud Sync",
    cloudSyncRestoreCta: "Restore Purchase",
    cloudSyncRetryCta: "Retry pending sync",
    cloudSyncRetryDetail: "Replace cloud data with this device to finish pending sync.",
    cloudSyncSyncCta: "Push this device to cloud",
    cloudSyncSyncDetail: "Replace cloud data with this device, then refresh from cloud.",
    cloudSyncSyncConfirm: "Replace your cloud data with the records currently on this device?",
    cloudSyncSyncDone: "Cloud replaced with {count} local records.",
    cloudSyncSyncFailed: "Cloud sync failed. Your local changes are still saved on this device.",
    cloudSyncPullCta: "Replace this device from cloud",
    cloudSyncPullDetail: "Discard pending local changes and download the latest cloud copy.",
    cloudSyncPullConfirm:
      "Replace the records on this device with the latest cloud data? Pending local changes on this device will be discarded.",
    cloudSyncPullDone: "Downloaded {count} cloud records to this device.",
    cloudSyncPullFailed: "Cloud download failed. Your current local data was kept.",
    iapNotReadyTitle: "Purchase not set up",
    iapNotReadyMessage:
      "Purchases are not configured for this build. Add RevenueCat keys and rebuild the app.",
    iapPackageUnavailableMessage: "This plan is not available in the current store offering.",
    iapErrorTitle: "Purchase failed",
    iapErrorMessage: "Please try again later.",
    localLimitTitle: "Local storage limit",
    localLimitValue: "{count} / {limit} records on this device",
    localLimitReachedTitle: "Limit reached",
    localLimitReachedMessage:
      "You reached the free local limit. Upgrade to Pro and sign in to unlock unlimited cloud storage.",
    localLimitReachedLocalOnlyMessage:
      "You reached the local record limit for this build. Remove some records to keep using this device.",
    storageUpgradeTitle: "Upgrade Storage Plan",
    storageUpgradeSubtitle: "Compare Basic, Plus, and Pro storage options.",
    storageUpgradeEyebrow: "Storage",
    storageUpgradeIntro:
      "Choose the plan that fits how you keep records: free local use, unlimited local storage, or cloud sync for multiple devices and shared books.",
    storagePlanCurrentBasic: "Current plan: Basic",
    storagePlanCurrentPlus: "Current plan: Plus",
    storagePlanCurrentPro: "Current plan: Pro",
    storagePlanCurrentBadge: "Current",
    storagePlanBasicTitle: "Basic Free",
    storagePlanBasicPrice: "USD $0",
    storagePlanBasicDescription: "Start accounting for free without signing in.",
    storagePlanBasicFeatureLimit: "Up to 200 records stored locally on this device.",
    storagePlanBasicFeatureNoLogin: "No account required.",
    storagePlanPlusTitle: "Plus Local",
    storagePlanPlusPrice: "USD $14.99 one-time",
    storagePlanPlusDescription: "For privacy-first users who want unlimited local records without a subscription.",
    storagePlanPlusFeatureUnlimited: "Unlimited local records.",
    storagePlanPlusFeaturePrivate: "Data stays on this device with no cloud account required.",
    storagePlanProTitle: "Pro Cloud",
    storagePlanProPrice: "{monthly} or {annual}",
    storagePlanProMonthlyFallback: "USD $5.99/month",
    storagePlanProAnnualFallback: "USD $59/year",
    storagePlanProDescription: "For multiple devices, phone changes, couples, families, and shared expenses.",
    storagePlanProFeatureSync: "Unlimited cloud records with automatic sync.",
    storagePlanProFeatureRestore: "Sign in across devices and restore after switching phones.",
    storagePlanProFeatureShared: "Shared books, reimbursements, settlement flow, and separate personal/shared views.",
    storagePlanProFeatureTravel: "Travel accounting.",
    storageUpgradeActionsTitle: "Upgrade when you are ready",
    storageUpgradeProAnnualCta: "Start Pro yearly · {price}",
    storageUpgradeProMonthlyCta: "Start Pro monthly · {price}",
    storageUpgradePlusCta: "Get Plus · {price}",
    storageUpgradePlusComingSoon: "Plus one-time purchase coming soon",
    "features.cloud-backup-sync.title": "Cloud Backup & Sync",
    "features.cloud-backup-sync.message":
      "Optional sign-in to sync across devices and restore data after reinstall.",
    "features.receipt-scan-ocr.title": "Receipt Scan + OCR",
    "features.receipt-scan-ocr.message":
      "Auto-fill amount and merchant information by scanning receipts.",
    "features.export-pdf-spreadsheet.title": "Export to PDF + Spreadsheet Templates",
    "features.export-pdf-spreadsheet.message":
      "Export your data to PDF and use spreadsheet templates for better organization.",
    comingSoon: "Coming Soon",
    dontShowAgain: "Don't Show Again",
    expense: "Expense",
    income: "Income",
    addExpense: "Add Expense",
    addIncome: "Add Income",
    smartLogExpense: "Smart Log Expense",
    smartLogIncome: "Smart Log Income",
    suggestedNames: "Suggested names",
    moneyFlowQuestion: "Where is the money going?",
    timeQuestion: "How am I doing over time?",
    pie: "Pie",
    treemap: "Treemap",
    bar: "Bars",
    line: "Line",
    spendingPie: "Spending Pie",
    spendingTreemap: "Spending Treemap",
    periodCompare: "Period Compare",
    spendingTrend: "Spending Trend",
    topFlow: "Top Flow",
    dailyAverage: "Daily Average",
    groups: "groups",
    noData: "No data",
    errorOccurred: "Something went wrong",
    errorMessage: "We encountered an unexpected error. Please try again or restart the app.",
    tryAgain: "Try Again",
    errorSaveFailed: "Failed to save. Please try again.",
    errorDeleteFailed: "Failed to delete. Please try again.",
    errorLoadFailed: "Failed to load data. Please try again.",
    errorInvalidAmount: "Please enter a valid amount greater than zero.",
    errorAmountTooLarge: "Amount is too large. Maximum is {max}.",
    errorDescriptionTooLong: "Description is too long. Maximum is {max} characters.",
    errorNetworkFailed: "Network error. Please check your connection.",
    errorDatabaseFailed: "Database error. Please restart the app.",
    loading: "Loading...",
    editEntry: "Edit Entry",
    save: "Save",
    saving: "Saving...",
    type: "Type",
    delete: "Delete",
    deleteEntry: "Delete Entry",
    deleteConfirmation: "Are you sure you want to delete this entry?",
    logDate: "Log Date",
  },
  zh: {
    accounting: "記帳",
    statistics: "統計",
    diagram: "圖表",
    total: "總計",
    count: "數量",
    flashAccounting: "黑白記帳",
    noConsumptionsYet: "尚無消費記錄",
    addFirstExpense: "請在上方新增您的第一筆支出",
    amount: "金額",
    description: "描述（選填）",
    noDescription: "無描述",
    add: "新增",
    byDay: "按日",
    byMonth: "按月",
    time: "時間",
    sort: "排序",
    all: "全部",
    today: "今天",
    week: "本週",
    month: "本月",
    year: "今年",
    newest: "最新",
    oldest: "最早",
    highest: "最高",
    lowest: "最低",
    today_label: "今天",
    yesterday: "昨天",
    items: "項",
    item: "項",
    noConsumptions: "未找到消費記錄",
    logDay: "記錄天數",
    rateThisApp: "評分應用",
    settings: "設定",
    exportCSV: "匯出為 CSV",
    selectLanguage: "選擇語言",
    clearHistory: "清除所有歷史",
    clearHistoryConfirm: "確定要清除所有歷史嗎？",
    cancel: "取消",
    confirm: "確認",
    english: "英語",
    chinese: "繁體中文",
    spanish: "西班牙語",
    french: "法語",
    german: "德語",
    japanese: "日語",
    device: "裝置語言",
    exportSuccess: "CSV 匯出成功！",
    exportError: "匯出 CSV 失敗",
    clearSuccess: "歷史記錄已清除",
    authFeatureTitle: "登入功能",
    authFeatureSubtitle: "可選登入，預設本機儲存。",
    authStatusSignedIn: "已登入",
    authStatusSignedOut: "未登入",
    authOptionalNote: "不登入也可以照常使用。",
    authContinueGoogle: "使用 Google 繼續",
    authContinueApple: "使用 Apple 繼續",
    authContinueFacebook: "使用 Facebook 繼續",
    authSignOut: "登出",
    authErrorTitle: "登入失敗",
    authErrorMessage: "請稍後再試一次。",
    authNotConfiguredTitle: "未設定登入",
    authNotConfiguredMessage: "此版本尚未設定 Firebase 登入。",
    cloudSyncTitle: "雲端同步（Pro）",
    cloudSyncActive: "已啟用 — 會儲存到雲端",
    cloudSyncStatusReady: "已就緒 — 裝置與雲端一致",
    cloudSyncStatusSyncing: "同步中",
    cloudSyncStatusPending: "此裝置有待同步的變更",
    cloudSyncStatusError: "同步需要處理",
    cloudSyncLockedSignedIn: "已登入 — 升級即可啟用雲端同步",
    cloudSyncLockedSignedOut: "登入並升級即可啟用雲端同步",
    cloudSyncLockedPaid: "已購買 — 登入後即可使用雲端同步",
    cloudSyncPendingDetail: "本機變更已安全保留。請把此裝置推送到雲端以完成同步。",
    cloudSyncErrorDetail: "目前無法確認雲端同步狀態。請檢查網路或手動重試。",
    cloudSyncLastSynced: "上次成功同步：{date}",
    cloudSyncNeverSynced: "尚未成功完成雲端同步",
    cloudSyncUpgradeCta: "解鎖雲端同步",
    cloudSyncMonthlyCta: "解鎖月繳雲端同步",
    cloudSyncAnnualCta: "解鎖年繳雲端同步",
    cloudSyncRestoreCta: "恢復購買",
    cloudSyncRetryCta: "重試待同步變更",
    cloudSyncRetryDetail: "以此裝置的資料覆蓋雲端，完成待同步變更。",
    cloudSyncSyncCta: "將此裝置推送到雲端",
    cloudSyncSyncDetail: "以此裝置資料覆蓋雲端，然後重新拉取雲端內容。",
    cloudSyncSyncConfirm: "要用此裝置目前的記錄覆蓋雲端資料嗎？",
    cloudSyncSyncDone: "已用 {count} 筆本機記錄覆蓋雲端。",
    cloudSyncSyncFailed: "雲端同步失敗，但本機變更仍安全保留。",
    cloudSyncPullCta: "用雲端資料覆蓋此裝置",
    cloudSyncPullDetail: "放棄待同步的本機變更，下載最新雲端內容。",
    cloudSyncPullConfirm: "要用最新雲端資料覆蓋此裝置記錄嗎？此裝置待同步的本機變更將被捨棄。",
    cloudSyncPullDone: "已下載 {count} 筆雲端記錄到此裝置。",
    cloudSyncPullFailed: "下載雲端資料失敗，目前本機資料已保留。",
    iapNotReadyTitle: "尚未設定購買",
    iapNotReadyMessage: "此版本尚未設定 RevenueCat 購買功能，請加入 API 金鑰並重新建置 App。",
    iapPackageUnavailableMessage: "此方案尚未在目前商店 offering 中上架。",
    iapErrorTitle: "購買失敗",
    iapErrorMessage: "請稍後再試。",
    localLimitTitle: "本機儲存上限",
    localLimitValue: "本機記錄：{count} / {limit}",
    localLimitReachedTitle: "已達上限",
    localLimitReachedMessage:
      "已達免費本機上限。升級 Pro 並登入即可解鎖無上限雲端儲存。",
    localLimitReachedLocalOnlyMessage:
      "此版本已達本機記錄上限。請先刪除部分記錄，再繼續在這台裝置上使用。",
    storageUpgradeTitle: "升級儲存方案",
    storageUpgradeSubtitle: "比較 Basic、Plus、Pro 的儲存選項。",
    storageUpgradeEyebrow: "儲存方案",
    storageUpgradeIntro:
      "依照你的記帳方式選擇方案：免費本機使用、本機無限記錄，或支援多裝置與共用帳本的雲端同步。",
    storagePlanCurrentBasic: "目前方案：Basic",
    storagePlanCurrentPlus: "目前方案：Plus",
    storagePlanCurrentPro: "目前方案：Pro",
    storagePlanCurrentBadge: "目前",
    storagePlanBasicTitle: "Basic 免費",
    storagePlanBasicPrice: "USD $0",
    storagePlanBasicDescription: "免登入即可免費開始記帳，適合先建立記帳習慣。",
    storagePlanBasicFeatureLimit: "本機最多保存 200 筆紀錄。",
    storagePlanBasicFeatureNoLogin: "不需要帳號即可使用。",
    storagePlanPlusTitle: "Plus 單機買斷",
    storagePlanPlusPrice: "USD $14.99 一次性買斷",
    storagePlanPlusDescription: "適合重視隱私、不想訂閱、也不需要雲端同步的使用者。",
    storagePlanPlusFeatureUnlimited: "本機無限記帳。",
    storagePlanPlusFeaturePrivate: "資料完整保存在本機，不需要雲端帳號。",
    storagePlanProTitle: "Pro 雲端與協作",
    storagePlanProPrice: "{monthly} 或 {annual}",
    storagePlanProMonthlyFallback: "USD $5.99/月",
    storagePlanProAnnualFallback: "USD $59/年",
    storagePlanProDescription: "適合多裝置、換機備份、伴侶、夫妻、家庭與共用支出管理。",
    storagePlanProFeatureSync: "雲端無限紀錄與自動同步。",
    storagePlanProFeatureRestore: "跨裝置登入，換手機也能還原資料。",
    storagePlanProFeatureShared: "雙人共用帳本、代墊拆帳、個人與共用視角。",
    storagePlanProFeatureTravel: "旅行記帳。",
    storageUpgradeActionsTitle: "準備好時再升級",
    storageUpgradeProAnnualCta: "啟用 Pro 年繳 · {price}",
    storageUpgradeProMonthlyCta: "啟用 Pro 月繳 · {price}",
    storageUpgradePlusCta: "購買 Plus · {price}",
    storageUpgradePlusComingSoon: "Plus 一次性買斷即將推出",
    "features.cloud-backup-sync.title": "雲端備份與同步",
    "features.cloud-backup-sync.message":
      "可選登入以跨裝置同步，並在重新安裝後還原資料。",
    "features.receipt-scan-ocr.title": "收據掃描 + OCR",
    "features.receipt-scan-ocr.message":
      "掃描收據即可自動填入金額和商家資訊。",
    "features.export-pdf-spreadsheet.title": "匯出至 PDF + 試算表範本",
    "features.export-pdf-spreadsheet.message":
      "將資料匯出為 PDF，並使用試算表範本以更好地組織資料。",
    comingSoon: "即將推出",
    dontShowAgain: "不再顯示",
    expense: "支出",
    income: "收入",
    addExpense: "新增支出",
    addIncome: "新增收入",
    smartLogExpense: "智慧記錄支出",
    smartLogIncome: "智慧記錄收入",
    suggestedNames: "建議名稱",
    moneyFlowQuestion: "錢花到哪裡了？",
    timeQuestion: "這段時間表現如何？",
    pie: "圓餅",
    treemap: "矩形圖",
    bar: "長條",
    line: "折線",
    spendingPie: "支出圓餅圖",
    spendingTreemap: "支出矩形圖",
    periodCompare: "期間比較",
    spendingTrend: "支出趨勢",
    topFlow: "主要流向",
    dailyAverage: "每日平均",
    groups: "類別",
    noData: "無資料",
    errorOccurred: "發生錯誤",
    errorMessage: "我們遇到了意外錯誤。請重試或重新啟動應用程式。",
    tryAgain: "重試",
    errorSaveFailed: "儲存失敗。請重試。",
    errorDeleteFailed: "刪除失敗。請重試。",
    errorLoadFailed: "載入資料失敗。請重試。",
    errorInvalidAmount: "請輸入大於零的有效金額。",
    errorAmountTooLarge: "金額過大。最大值為 {max}。",
    errorDescriptionTooLong: "描述過長。最多 {max} 個字元。",
    errorNetworkFailed: "網路錯誤。請檢查您的連線。",
    errorDatabaseFailed: "資料庫錯誤。請重新啟動應用程式。",
    loading: "載入中...",
    editEntry: "編輯記錄",
    save: "儲存",
    saving: "儲存中...",
    type: "類型",
    delete: "刪除",
    deleteEntry: "刪除記錄",
    deleteConfirmation: "確定要刪除此記錄嗎？",
    logDate: "記錄日期",
  },
  es: {
    accounting: "Contabilidad",
    statistics: "Estadísticas",
    diagram: "Diagrama",
    total: "Total",
    count: "Cantidad",
    flashAccounting: "Contabilidad Blanco Negro",
    noConsumptionsYet: "Aún no hay consumos",
    addFirstExpense: "Agrega tu primer gasto arriba",
    amount: "Cantidad",
    description: "Descripción (opcional)",
    noDescription: "Sin descripción",
    add: "Agregar",
    byDay: "Por Día",
    byMonth: "Por Mes",
    time: "Tiempo",
    sort: "Ordenar",
    all: "Todo",
    today: "Hoy",
    week: "Semana",
    month: "Mes",
    year: "Año",
    newest: "Más reciente",
    oldest: "Más antiguo",
    highest: "Mayor",
    lowest: "Menor",
    today_label: "Hoy",
    yesterday: "Ayer",
    items: "elementos",
    item: "elemento",
    noConsumptions: "No se encontraron consumos",
    logDay: "Días Registrados",
    rateThisApp: "Calificar App",
    settings: "Configuración",
    exportCSV: "Exportar a CSV",
    selectLanguage: "Seleccionar idioma",
    clearHistory: "Borrar todo el historial",
    clearHistoryConfirm:
      "¿Estás seguro de que quieres borrar todo el historial?",
    cancel: "Cancelar",
    confirm: "Confirmar",
    english: "Inglés",
    chinese: "Chino Tradicional",
    spanish: "Español",
    french: "Francés",
    german: "Alemán",
    japanese: "Japonés",
    device: "Idioma del Dispositivo",
    exportSuccess: "¡CSV exportado con éxito!",
    exportError: "Error al exportar CSV",
    clearSuccess: "Historial borrado con éxito",
    authFeatureTitle: "Auth feature",
    authFeatureSubtitle: "Optional sign-in. Local-first by default.",
    authStatusSignedIn: "Signed in",
    authStatusSignedOut: "Not signed in",
    authOptionalNote: "You can keep using the app without signing in.",
    authContinueGoogle: "Continue with Google",
    authContinueApple: "Continue with Apple",
    authContinueFacebook: "Continue with Facebook",
    authSignOut: "Sign out",
    authErrorTitle: "Sign-in failed",
    authErrorMessage: "Please try again.",
    authNotConfiguredTitle: "Auth not configured",
    authNotConfiguredMessage: "Firebase auth is not configured for this build.",
    cloudSyncTitle: "Cloud Sync (Pro)",
    cloudSyncActive: "Active — saving to cloud",
    cloudSyncStatusReady: "Ready — device and cloud match",
    cloudSyncStatusSyncing: "Syncing now",
    cloudSyncStatusPending: "Pending local changes",
    cloudSyncStatusError: "Sync needs attention",
    cloudSyncLockedSignedIn: "Signed in — upgrade to enable cloud sync",
    cloudSyncLockedSignedOut: "Sign in + upgrade to enable cloud sync",
    cloudSyncLockedPaid: "Purchased — sign in to use cloud sync",
    cloudSyncPendingDetail:
      "Local changes are safe on this device. Push this device to cloud to finish syncing.",
    cloudSyncErrorDetail:
      "Cloud sync could not be checked. Review your connection or retry manually.",
    cloudSyncLastSynced: "Last successful sync: {date}",
    cloudSyncNeverSynced: "No successful cloud sync yet",
    cloudSyncUpgradeCta: "Unlock Cloud Sync",
    cloudSyncMonthlyCta: "Get Monthly Cloud Sync",
    cloudSyncAnnualCta: "Get Yearly Cloud Sync",
    cloudSyncRestoreCta: "Restore Purchase",
    cloudSyncRetryCta: "Retry pending sync",
    cloudSyncRetryDetail: "Replace cloud data with this device to finish pending sync.",
    cloudSyncSyncCta: "Push this device to cloud",
    cloudSyncSyncDetail: "Replace cloud data with this device, then refresh from cloud.",
    cloudSyncSyncConfirm: "Replace your cloud data with the records currently on this device?",
    cloudSyncSyncDone: "Cloud replaced with {count} local records.",
    cloudSyncSyncFailed: "Cloud sync failed. Your local changes are still saved on this device.",
    cloudSyncPullCta: "Replace this device from cloud",
    cloudSyncPullDetail: "Discard pending local changes and download the latest cloud copy.",
    cloudSyncPullConfirm:
      "Replace the records on this device with the latest cloud data? Pending local changes on this device will be discarded.",
    cloudSyncPullDone: "Downloaded {count} cloud records to this device.",
    cloudSyncPullFailed: "Cloud download failed. Your current local data was kept.",
    iapNotReadyTitle: "Purchase not set up",
    iapNotReadyMessage:
      "Purchases are not configured for this build. Add RevenueCat keys and rebuild the app.",
    iapPackageUnavailableMessage: "This plan is not available in the current store offering.",
    iapErrorTitle: "Purchase failed",
    iapErrorMessage: "Please try again later.",
    localLimitTitle: "Local storage limit",
    localLimitValue: "{count} / {limit} records on this device",
    localLimitReachedTitle: "Limit reached",
    localLimitReachedMessage:
      "You reached the free local limit. Upgrade to Pro and sign in to unlock unlimited cloud storage.",
    localLimitReachedLocalOnlyMessage:
      "Has alcanzado el limite de registros locales de esta version. Elimina algunos registros para seguir usando este dispositivo.",
    storageUpgradeTitle: "Upgrade Storage Plan",
    storageUpgradeSubtitle: "Compare Basic, Plus, and Pro storage options.",
    storageUpgradeEyebrow: "Storage",
    storageUpgradeIntro:
      "Choose the plan that fits how you keep records: free local use, unlimited local storage, or cloud sync for multiple devices and shared books.",
    storagePlanCurrentBasic: "Current plan: Basic",
    storagePlanCurrentPlus: "Current plan: Plus",
    storagePlanCurrentPro: "Current plan: Pro",
    storagePlanCurrentBadge: "Current",
    storagePlanBasicTitle: "Basic Free",
    storagePlanBasicPrice: "USD $0",
    storagePlanBasicDescription: "Start accounting for free without signing in.",
    storagePlanBasicFeatureLimit: "Up to 200 records stored locally on this device.",
    storagePlanBasicFeatureNoLogin: "No account required.",
    storagePlanPlusTitle: "Plus Local",
    storagePlanPlusPrice: "USD $14.99 one-time",
    storagePlanPlusDescription: "For privacy-first users who want unlimited local records without a subscription.",
    storagePlanPlusFeatureUnlimited: "Unlimited local records.",
    storagePlanPlusFeaturePrivate: "Data stays on this device with no cloud account required.",
    storagePlanProTitle: "Pro Cloud",
    storagePlanProPrice: "{monthly} or {annual}",
    storagePlanProMonthlyFallback: "USD $5.99/month",
    storagePlanProAnnualFallback: "USD $59/year",
    storagePlanProDescription: "For multiple devices, phone changes, couples, families, and shared expenses.",
    storagePlanProFeatureSync: "Unlimited cloud records with automatic sync.",
    storagePlanProFeatureRestore: "Sign in across devices and restore after switching phones.",
    storagePlanProFeatureShared: "Shared books, reimbursements, settlement flow, and separate personal/shared views.",
    storagePlanProFeatureTravel: "Travel accounting.",
    storageUpgradeActionsTitle: "Upgrade when you are ready",
    storageUpgradeProAnnualCta: "Start Pro yearly · {price}",
    storageUpgradeProMonthlyCta: "Start Pro monthly · {price}",
    storageUpgradePlusCta: "Get Plus · {price}",
    storageUpgradePlusComingSoon: "Plus one-time purchase coming soon",
    "features.cloud-backup-sync.title": "Respaldo en la Nube y Sincronización",
    "features.cloud-backup-sync.message":
      "Inicio de sesión opcional para sincronizar entre dispositivos y restaurar datos después de reinstalar.",
    "features.receipt-scan-ocr.title": "Escaneo de Recibos + OCR",
    "features.receipt-scan-ocr.message":
      "Llena automáticamente el monto y la información del comerciante escaneando recibos.",
    "features.export-pdf-spreadsheet.title": "Exportar a PDF + Plantillas de Hoja de Cálculo",
    "features.export-pdf-spreadsheet.message":
      "Exporta tus datos a PDF y usa plantillas de hoja de cálculo para una mejor organización.",
    comingSoon: "Próximamente",
    dontShowAgain: "No Mostrar de Nuevo",
    expense: "Gasto",
    income: "Ingreso",
    addExpense: "Agregar Gasto",
    addIncome: "Agregar Ingreso",
    smartLogExpense: "Registro inteligente de gastos",
    smartLogIncome: "Registro inteligente de ingresos",
    suggestedNames: "Nombres sugeridos",
    moneyFlowQuestion: "¿A dónde va el dinero?",
    timeQuestion: "¿Cómo voy con el tiempo?",
    pie: "Circular",
    treemap: "Mapa de áreas",
    bar: "Barras",
    line: "Línea",
    spendingPie: "Gráfico circular de gastos",
    spendingTreemap: "Mapa de áreas de gastos",
    periodCompare: "Comparación por periodo",
    spendingTrend: "Tendencia de gastos",
    topFlow: "Mayor flujo",
    dailyAverage: "Promedio diario",
    groups: "grupos",
    noData: "Sin datos",
    errorOccurred: "Algo salió mal",
    errorMessage: "Encontramos un error inesperado. Por favor, inténtalo de nuevo o reinicia la aplicación.",
    tryAgain: "Intentar de Nuevo",
    errorSaveFailed: "Error al guardar. Por favor, inténtalo de nuevo.",
    errorDeleteFailed: "Error al eliminar. Por favor, inténtalo de nuevo.",
    errorLoadFailed: "Error al cargar datos. Por favor, inténtalo de nuevo.",
    errorInvalidAmount: "Por favor, ingresa una cantidad válida mayor que cero.",
    errorAmountTooLarge: "La cantidad es demasiado grande. El máximo es {max}.",
    errorDescriptionTooLong: "La descripción es demasiado larga. El máximo es {max} caracteres.",
    errorNetworkFailed: "Error de red. Por favor, verifica tu conexión.",
    errorDatabaseFailed: "Error de base de datos. Por favor, reinicia la aplicación.",
    loading: "Cargando...",
    editEntry: "Editar entrada",
    save: "Guardar",
    saving: "Guardando...",
    type: "Tipo",
    delete: "Eliminar",
    deleteEntry: "Eliminar entrada",
    deleteConfirmation: "¿Estás seguro de que quieres eliminar esta entrada?",
    logDate: "Fecha del registro",
  },
  fr: {
    accounting: "Comptabilité",
    statistics: "Statistiques",
    diagram: "Graphique",
    total: "Total",
    count: "Nombre",
    flashAccounting: "Comptabilité Blanc Noir",
    noConsumptionsYet: "Aucune consommation pour le moment",
    addFirstExpense: "Ajoutez votre première dépense ci-dessus",
    amount: "Montant",
    description: "Description (optionnel)",
    noDescription: "Aucune description",
    add: "Ajouter",
    byDay: "Par Jour",
    byMonth: "Par Mois",
    time: "Temps",
    sort: "Trier",
    all: "Tout",
    today: "Aujourd'hui",
    week: "Semaine",
    month: "Mois",
    year: "Année",
    newest: "Plus récent",
    oldest: "Plus ancien",
    highest: "Le plus élevé",
    lowest: "Le plus bas",
    today_label: "Aujourd'hui",
    yesterday: "Hier",
    items: "éléments",
    item: "élément",
    noConsumptions: "Aucune consommation trouvée",
    logDay: "Jours d'Enregistrement",
    rateThisApp: "Noter l'App",
    settings: "Paramètres",
    exportCSV: "Exporter en CSV",
    selectLanguage: "Sélectionner la langue",
    clearHistory: "Effacer tout l'historique",
    clearHistoryConfirm: "Êtes-vous sûr de vouloir effacer tout l'historique?",
    cancel: "Annuler",
    confirm: "Confirmer",
    english: "Anglais",
    chinese: "Chinois Traditionnel",
    spanish: "Espagnol",
    french: "Français",
    german: "Allemand",
    japanese: "Japonais",
    device: "Langue de l'Appareil",
    exportSuccess: "CSV exporté avec succès!",
    exportError: "Échec de l'exportation CSV",
    clearSuccess: "Historique effacé avec succès",
    authFeatureTitle: "Auth feature",
    authFeatureSubtitle: "Optional sign-in. Local-first by default.",
    authStatusSignedIn: "Signed in",
    authStatusSignedOut: "Not signed in",
    authOptionalNote: "You can keep using the app without signing in.",
    authContinueGoogle: "Continue with Google",
    authContinueApple: "Continue with Apple",
    authContinueFacebook: "Continue with Facebook",
    authSignOut: "Sign out",
    authErrorTitle: "Sign-in failed",
    authErrorMessage: "Please try again.",
    authNotConfiguredTitle: "Auth not configured",
    authNotConfiguredMessage: "Firebase auth is not configured for this build.",
    cloudSyncTitle: "Cloud Sync (Pro)",
    cloudSyncActive: "Active — saving to cloud",
    cloudSyncStatusReady: "Ready — device and cloud match",
    cloudSyncStatusSyncing: "Syncing now",
    cloudSyncStatusPending: "Pending local changes",
    cloudSyncStatusError: "Sync needs attention",
    cloudSyncLockedSignedIn: "Signed in — upgrade to enable cloud sync",
    cloudSyncLockedSignedOut: "Sign in + upgrade to enable cloud sync",
    cloudSyncLockedPaid: "Purchased — sign in to use cloud sync",
    cloudSyncPendingDetail:
      "Local changes are safe on this device. Push this device to cloud to finish syncing.",
    cloudSyncErrorDetail:
      "Cloud sync could not be checked. Review your connection or retry manually.",
    cloudSyncLastSynced: "Last successful sync: {date}",
    cloudSyncNeverSynced: "No successful cloud sync yet",
    cloudSyncUpgradeCta: "Unlock Cloud Sync",
    cloudSyncMonthlyCta: "Get Monthly Cloud Sync",
    cloudSyncAnnualCta: "Get Yearly Cloud Sync",
    cloudSyncRestoreCta: "Restore Purchase",
    cloudSyncRetryCta: "Retry pending sync",
    cloudSyncRetryDetail: "Replace cloud data with this device to finish pending sync.",
    cloudSyncSyncCta: "Push this device to cloud",
    cloudSyncSyncDetail: "Replace cloud data with this device, then refresh from cloud.",
    cloudSyncSyncConfirm: "Replace your cloud data with the records currently on this device?",
    cloudSyncSyncDone: "Cloud replaced with {count} local records.",
    cloudSyncSyncFailed: "Cloud sync failed. Your local changes are still saved on this device.",
    cloudSyncPullCta: "Replace this device from cloud",
    cloudSyncPullDetail: "Discard pending local changes and download the latest cloud copy.",
    cloudSyncPullConfirm:
      "Replace the records on this device with the latest cloud data? Pending local changes on this device will be discarded.",
    cloudSyncPullDone: "Downloaded {count} cloud records to this device.",
    cloudSyncPullFailed: "Cloud download failed. Your current local data was kept.",
    iapNotReadyTitle: "Purchase not set up",
    iapNotReadyMessage:
      "Purchases are not configured for this build. Add RevenueCat keys and rebuild the app.",
    iapPackageUnavailableMessage: "This plan is not available in the current store offering.",
    iapErrorTitle: "Purchase failed",
    iapErrorMessage: "Please try again later.",
    localLimitTitle: "Local storage limit",
    localLimitValue: "{count} / {limit} records on this device",
    localLimitReachedTitle: "Limit reached",
    localLimitReachedMessage:
      "You reached the free local limit. Upgrade to Pro and sign in to unlock unlimited cloud storage.",
    localLimitReachedLocalOnlyMessage:
      "Vous avez atteint la limite d'enregistrements locaux pour cette version. Supprimez quelques entrees pour continuer a utiliser cet appareil.",
    storageUpgradeTitle: "Upgrade Storage Plan",
    storageUpgradeSubtitle: "Compare Basic, Plus, and Pro storage options.",
    storageUpgradeEyebrow: "Storage",
    storageUpgradeIntro:
      "Choose the plan that fits how you keep records: free local use, unlimited local storage, or cloud sync for multiple devices and shared books.",
    storagePlanCurrentBasic: "Current plan: Basic",
    storagePlanCurrentPlus: "Current plan: Plus",
    storagePlanCurrentPro: "Current plan: Pro",
    storagePlanCurrentBadge: "Current",
    storagePlanBasicTitle: "Basic Free",
    storagePlanBasicPrice: "USD $0",
    storagePlanBasicDescription: "Start accounting for free without signing in.",
    storagePlanBasicFeatureLimit: "Up to 200 records stored locally on this device.",
    storagePlanBasicFeatureNoLogin: "No account required.",
    storagePlanPlusTitle: "Plus Local",
    storagePlanPlusPrice: "USD $14.99 one-time",
    storagePlanPlusDescription: "For privacy-first users who want unlimited local records without a subscription.",
    storagePlanPlusFeatureUnlimited: "Unlimited local records.",
    storagePlanPlusFeaturePrivate: "Data stays on this device with no cloud account required.",
    storagePlanProTitle: "Pro Cloud",
    storagePlanProPrice: "{monthly} or {annual}",
    storagePlanProMonthlyFallback: "USD $5.99/month",
    storagePlanProAnnualFallback: "USD $59/year",
    storagePlanProDescription: "For multiple devices, phone changes, couples, families, and shared expenses.",
    storagePlanProFeatureSync: "Unlimited cloud records with automatic sync.",
    storagePlanProFeatureRestore: "Sign in across devices and restore after switching phones.",
    storagePlanProFeatureShared: "Shared books, reimbursements, settlement flow, and separate personal/shared views.",
    storagePlanProFeatureTravel: "Travel accounting.",
    storageUpgradeActionsTitle: "Upgrade when you are ready",
    storageUpgradeProAnnualCta: "Start Pro yearly · {price}",
    storageUpgradeProMonthlyCta: "Start Pro monthly · {price}",
    storageUpgradePlusCta: "Get Plus · {price}",
    storageUpgradePlusComingSoon: "Plus one-time purchase coming soon",
    "features.cloud-backup-sync.title": "Sauvegarde Cloud et Synchronisation",
    "features.cloud-backup-sync.message":
      "Connexion optionnelle pour synchroniser entre les appareils et restaurer les données après réinstallation.",
    "features.receipt-scan-ocr.title": "Scan de Reçus + OCR",
    "features.receipt-scan-ocr.message":
      "Remplissage automatique du montant et des informations du commerçant en scannant les reçus.",
    "features.export-pdf-spreadsheet.title": "Exporter vers PDF + Modèles de Tableur",
    "features.export-pdf-spreadsheet.message":
      "Exportez vos données vers PDF et utilisez des modèles de tableur pour une meilleure organisation.",
    comingSoon: "Bientôt Disponible",
    dontShowAgain: "Ne Plus Afficher",
    expense: "Dépense",
    income: "Revenu",
    addExpense: "Ajouter Dépense",
    addIncome: "Ajouter Revenu",
    smartLogExpense: "Saisie intelligente de dépense",
    smartLogIncome: "Saisie intelligente de revenu",
    suggestedNames: "Noms suggérés",
    moneyFlowQuestion: "Où va l'argent ?",
    timeQuestion: "Comment je m'en sors dans le temps ?",
    pie: "Camembert",
    treemap: "Treemap",
    bar: "Barres",
    line: "Courbe",
    spendingPie: "Camembert des dépenses",
    spendingTreemap: "Treemap des dépenses",
    periodCompare: "Comparaison par période",
    spendingTrend: "Tendance des dépenses",
    topFlow: "Flux principal",
    dailyAverage: "Moyenne quotidienne",
    groups: "groupes",
    noData: "Aucune donnée",
    errorOccurred: "Une erreur s'est produite",
    errorMessage: "Nous avons rencontré une erreur inattendue. Veuillez réessayer ou redémarrer l'application.",
    tryAgain: "Réessayer",
    errorSaveFailed: "Échec de l'enregistrement. Veuillez réessayer.",
    errorDeleteFailed: "Échec de la suppression. Veuillez réessayer.",
    errorLoadFailed: "Échec du chargement des données. Veuillez réessayer.",
    errorInvalidAmount: "Veuillez entrer un montant valide supérieur à zéro.",
    errorAmountTooLarge: "Le montant est trop élevé. Le maximum est {max}.",
    errorDescriptionTooLong: "La description est trop longue. Le maximum est {max} caractères.",
    errorNetworkFailed: "Erreur réseau. Veuillez vérifier votre connexion.",
    errorDatabaseFailed: "Erreur de base de données. Veuillez redémarrer l'application.",
    loading: "Chargement...",
    editEntry: "Modifier l'entrée",
    save: "Enregistrer",
    saving: "Enregistrement...",
    type: "Type",
    delete: "Supprimer",
    deleteEntry: "Supprimer l'entrée",
    deleteConfirmation: "Êtes-vous sûr de vouloir supprimer cette entrée?",
    logDate: "Date du journal",
  },
  de: {
    accounting: "Buchhaltung",
    statistics: "Statistiken",
    diagram: "Diagramm",
    total: "Gesamt",
    count: "Anzahl",
    flashAccounting: "Schwarz Weiß Buchhaltung",
    noConsumptionsYet: "Noch keine Verbräuche",
    addFirstExpense: "Fügen Sie oben Ihre erste Ausgabe hinzu",
    amount: "Betrag",
    description: "Beschreibung (optional)",
    noDescription: "Keine Beschreibung",
    add: "Hinzufügen",
    byDay: "Nach Tag",
    byMonth: "Nach Monat",
    time: "Zeit",
    sort: "Sortieren",
    all: "Alle",
    today: "Heute",
    week: "Woche",
    month: "Monat",
    year: "Jahr",
    newest: "Neueste",
    oldest: "Älteste",
    highest: "Höchste",
    lowest: "Niedrigste",
    today_label: "Heute",
    yesterday: "Gestern",
    items: "Elemente",
    item: "Element",
    noConsumptions: "Keine Verbräuche gefunden",
    logDay: "Registriertage",
    rateThisApp: "App Bewerten",
    settings: "Einstellungen",
    exportCSV: "Als CSV exportieren",
    selectLanguage: "Sprache auswählen",
    clearHistory: "Gesamten Verlauf löschen",
    clearHistoryConfirm:
      "Sind Sie sicher, dass Sie den gesamten Verlauf löschen möchten?",
    cancel: "Abbrechen",
    confirm: "Bestätigen",
    english: "Englisch",
    chinese: "Traditionelles Chinesisch",
    spanish: "Spanisch",
    french: "Französisch",
    german: "Deutsch",
    japanese: "Japanisch",
    device: "Gerätesprache",
    exportSuccess: "CSV erfolgreich exportiert!",
    exportError: "CSV-Export fehlgeschlagen",
    clearSuccess: "Verlauf erfolgreich gelöscht",
    authFeatureTitle: "Auth feature",
    authFeatureSubtitle: "Optional sign-in. Local-first by default.",
    authStatusSignedIn: "Signed in",
    authStatusSignedOut: "Not signed in",
    authOptionalNote: "You can keep using the app without signing in.",
    authContinueGoogle: "Continue with Google",
    authContinueApple: "Continue with Apple",
    authContinueFacebook: "Continue with Facebook",
    authSignOut: "Sign out",
    authErrorTitle: "Sign-in failed",
    authErrorMessage: "Please try again.",
    authNotConfiguredTitle: "Auth not configured",
    authNotConfiguredMessage: "Firebase auth is not configured for this build.",
    cloudSyncTitle: "Cloud Sync (Pro)",
    cloudSyncActive: "Active — saving to cloud",
    cloudSyncStatusReady: "Ready — device and cloud match",
    cloudSyncStatusSyncing: "Syncing now",
    cloudSyncStatusPending: "Pending local changes",
    cloudSyncStatusError: "Sync needs attention",
    cloudSyncLockedSignedIn: "Signed in — upgrade to enable cloud sync",
    cloudSyncLockedSignedOut: "Sign in + upgrade to enable cloud sync",
    cloudSyncLockedPaid: "Purchased — sign in to use cloud sync",
    cloudSyncPendingDetail:
      "Local changes are safe on this device. Push this device to cloud to finish syncing.",
    cloudSyncErrorDetail:
      "Cloud sync could not be checked. Review your connection or retry manually.",
    cloudSyncLastSynced: "Last successful sync: {date}",
    cloudSyncNeverSynced: "No successful cloud sync yet",
    cloudSyncUpgradeCta: "Unlock Cloud Sync",
    cloudSyncMonthlyCta: "Get Monthly Cloud Sync",
    cloudSyncAnnualCta: "Get Yearly Cloud Sync",
    cloudSyncRestoreCta: "Restore Purchase",
    cloudSyncRetryCta: "Retry pending sync",
    cloudSyncRetryDetail: "Replace cloud data with this device to finish pending sync.",
    cloudSyncSyncCta: "Push this device to cloud",
    cloudSyncSyncDetail: "Replace cloud data with this device, then refresh from cloud.",
    cloudSyncSyncConfirm: "Replace your cloud data with the records currently on this device?",
    cloudSyncSyncDone: "Cloud replaced with {count} local records.",
    cloudSyncSyncFailed: "Cloud sync failed. Your local changes are still saved on this device.",
    cloudSyncPullCta: "Replace this device from cloud",
    cloudSyncPullDetail: "Discard pending local changes and download the latest cloud copy.",
    cloudSyncPullConfirm:
      "Replace the records on this device with the latest cloud data? Pending local changes on this device will be discarded.",
    cloudSyncPullDone: "Downloaded {count} cloud records to this device.",
    cloudSyncPullFailed: "Cloud download failed. Your current local data was kept.",
    iapNotReadyTitle: "Purchase not set up",
    iapNotReadyMessage:
      "Purchases are not configured for this build. Add RevenueCat keys and rebuild the app.",
    iapPackageUnavailableMessage: "This plan is not available in the current store offering.",
    iapErrorTitle: "Purchase failed",
    iapErrorMessage: "Please try again later.",
    localLimitTitle: "Local storage limit",
    localLimitValue: "{count} / {limit} records on this device",
    localLimitReachedTitle: "Limit reached",
    localLimitReachedMessage:
      "You reached the free local limit. Upgrade to Pro and sign in to unlock unlimited cloud storage.",
    localLimitReachedLocalOnlyMessage:
      "Sie haben das lokale Datensatzlimit fur diese Version erreicht. Loschen Sie einige Eintrage, um dieses Gerat weiter zu verwenden.",
    storageUpgradeTitle: "Upgrade Storage Plan",
    storageUpgradeSubtitle: "Compare Basic, Plus, and Pro storage options.",
    storageUpgradeEyebrow: "Storage",
    storageUpgradeIntro:
      "Choose the plan that fits how you keep records: free local use, unlimited local storage, or cloud sync for multiple devices and shared books.",
    storagePlanCurrentBasic: "Current plan: Basic",
    storagePlanCurrentPlus: "Current plan: Plus",
    storagePlanCurrentPro: "Current plan: Pro",
    storagePlanCurrentBadge: "Current",
    storagePlanBasicTitle: "Basic Free",
    storagePlanBasicPrice: "USD $0",
    storagePlanBasicDescription: "Start accounting for free without signing in.",
    storagePlanBasicFeatureLimit: "Up to 200 records stored locally on this device.",
    storagePlanBasicFeatureNoLogin: "No account required.",
    storagePlanPlusTitle: "Plus Local",
    storagePlanPlusPrice: "USD $14.99 one-time",
    storagePlanPlusDescription: "For privacy-first users who want unlimited local records without a subscription.",
    storagePlanPlusFeatureUnlimited: "Unlimited local records.",
    storagePlanPlusFeaturePrivate: "Data stays on this device with no cloud account required.",
    storagePlanProTitle: "Pro Cloud",
    storagePlanProPrice: "{monthly} or {annual}",
    storagePlanProMonthlyFallback: "USD $5.99/month",
    storagePlanProAnnualFallback: "USD $59/year",
    storagePlanProDescription: "For multiple devices, phone changes, couples, families, and shared expenses.",
    storagePlanProFeatureSync: "Unlimited cloud records with automatic sync.",
    storagePlanProFeatureRestore: "Sign in across devices and restore after switching phones.",
    storagePlanProFeatureShared: "Shared books, reimbursements, settlement flow, and separate personal/shared views.",
    storagePlanProFeatureTravel: "Travel accounting.",
    storageUpgradeActionsTitle: "Upgrade when you are ready",
    storageUpgradeProAnnualCta: "Start Pro yearly · {price}",
    storageUpgradeProMonthlyCta: "Start Pro monthly · {price}",
    storageUpgradePlusCta: "Get Plus · {price}",
    storageUpgradePlusComingSoon: "Plus one-time purchase coming soon",
    "features.cloud-backup-sync.title": "Cloud-Backup & Synchronisation",
    "features.cloud-backup-sync.message":
      "Optionaler Anmeldung zur Synchronisation zwischen Geräten und Wiederherstellung von Daten nach Neuinstallation.",
    "features.receipt-scan-ocr.title": "Beleg-Scan + OCR",
    "features.receipt-scan-ocr.message":
      "Automatisches Ausfüllen von Betrag und Händlerinformationen durch Scannen von Belegen.",
    "features.export-pdf-spreadsheet.title": "Export nach PDF + Tabellenkalkulationsvorlagen",
    "features.export-pdf-spreadsheet.message":
      "Exportieren Sie Ihre Daten nach PDF und verwenden Sie Tabellenkalkulationsvorlagen für bessere Organisation.",
    comingSoon: "Demnächst",
    dontShowAgain: "Nicht Mehr Anzeigen",
    expense: "Ausgabe",
    income: "Einnahme",
    addExpense: "Ausgabe Hinzufügen",
    addIncome: "Einnahme Hinzufügen",
    smartLogExpense: "Intelligente Ausgabe erfassen",
    smartLogIncome: "Intelligente Einnahme erfassen",
    suggestedNames: "Vorgeschlagene Namen",
    moneyFlowQuestion: "Wohin fließt das Geld?",
    timeQuestion: "Wie entwickle ich mich über die Zeit?",
    pie: "Kreis",
    treemap: "Treemap",
    bar: "Balken",
    line: "Linie",
    spendingPie: "Ausgaben-Kreisdiagramm",
    spendingTreemap: "Ausgaben-Treemap",
    periodCompare: "Periodenvergleich",
    spendingTrend: "Ausgabentrend",
    topFlow: "Top-Kategorie",
    dailyAverage: "Tagesdurchschnitt",
    groups: "Gruppen",
    noData: "Keine Daten",
    errorOccurred: "Ein Fehler ist aufgetreten",
    errorMessage: "Wir haben einen unerwarteten Fehler festgestellt. Bitte versuchen Sie es erneut oder starten Sie die App neu.",
    tryAgain: "Erneut Versuchen",
    errorSaveFailed: "Speichern fehlgeschlagen. Bitte versuchen Sie es erneut.",
    errorDeleteFailed: "Löschen fehlgeschlagen. Bitte versuchen Sie es erneut.",
    errorLoadFailed: "Daten laden fehlgeschlagen. Bitte versuchen Sie es erneut.",
    errorInvalidAmount: "Bitte geben Sie einen gültigen Betrag größer als null ein.",
    errorAmountTooLarge: "Der Betrag ist zu groß. Das Maximum ist {max}.",
    errorDescriptionTooLong: "Die Beschreibung ist zu lang. Das Maximum ist {max} Zeichen.",
    errorNetworkFailed: "Netzwerkfehler. Bitte überprüfen Sie Ihre Verbindung.",
    errorDatabaseFailed: "Datenbankfehler. Bitte starten Sie die App neu.",
    loading: "Laden...",
    editEntry: "Eintrag bearbeiten",
    save: "Speichern",
    saving: "Speichern...",
    type: "Typ",
    delete: "Löschen",
    deleteEntry: "Eintrag löschen",
    deleteConfirmation: "Sind Sie sicher, dass Sie diesen Eintrag löschen möchten?",
    logDate: "Buchungsdatum",
  },
  ja: {
    accounting: "会計",
    statistics: "統計",
    diagram: "グラフ",
    total: "合計",
    count: "件数",
    flashAccounting: "白黒会計",
    noConsumptionsYet: "消費がまだありません",
    addFirstExpense: "上記に最初の支出を追加してください",
    amount: "金額",
    description: "説明（任意）",
    noDescription: "説明なし",
    add: "追加",
    byDay: "日別",
    byMonth: "月別",
    time: "時間",
    sort: "並び替え",
    all: "全て",
    today: "今日",
    week: "今週",
    month: "今月",
    year: "今年",
    newest: "最新",
    oldest: "最古",
    highest: "最高",
    lowest: "最低",
    today_label: "今日",
    yesterday: "昨日",
    items: "件",
    item: "件",
    noConsumptions: "消費が見つかりません",
    logDay: "記録日数",
    rateThisApp: "アプリを評価",
    settings: "設定",
    exportCSV: "CSVにエクスポート",
    selectLanguage: "言語を選択",
    clearHistory: "履歴をすべてクリア",
    clearHistoryConfirm: "すべての履歴をクリアしてもよろしいですか？",
    cancel: "キャンセル",
    confirm: "確認",
    english: "英語",
    chinese: "繁体中国語",
    spanish: "スペイン語",
    french: "フランス語",
    german: "ドイツ語",
    japanese: "日本語",
    device: "デバイス言語",
    exportSuccess: "CSVのエクスポートに成功しました！",
    exportError: "CSVのエクスポートに失敗しました",
    clearSuccess: "履歴がクリアされました",
    authFeatureTitle: "Auth feature",
    authFeatureSubtitle: "Optional sign-in. Local-first by default.",
    authStatusSignedIn: "Signed in",
    authStatusSignedOut: "Not signed in",
    authOptionalNote: "You can keep using the app without signing in.",
    authContinueGoogle: "Continue with Google",
    authContinueApple: "Continue with Apple",
    authContinueFacebook: "Continue with Facebook",
    authSignOut: "Sign out",
    authErrorTitle: "Sign-in failed",
    authErrorMessage: "Please try again.",
    authNotConfiguredTitle: "Auth not configured",
    authNotConfiguredMessage: "Firebase auth is not configured for this build.",
    cloudSyncTitle: "Cloud Sync (Pro)",
    cloudSyncActive: "Active — saving to cloud",
    cloudSyncStatusReady: "Ready — device and cloud match",
    cloudSyncStatusSyncing: "Syncing now",
    cloudSyncStatusPending: "Pending local changes",
    cloudSyncStatusError: "Sync needs attention",
    cloudSyncLockedSignedIn: "Signed in — upgrade to enable cloud sync",
    cloudSyncLockedSignedOut: "Sign in + upgrade to enable cloud sync",
    cloudSyncLockedPaid: "Purchased — sign in to use cloud sync",
    cloudSyncPendingDetail:
      "Local changes are safe on this device. Push this device to cloud to finish syncing.",
    cloudSyncErrorDetail:
      "Cloud sync could not be checked. Review your connection or retry manually.",
    cloudSyncLastSynced: "Last successful sync: {date}",
    cloudSyncNeverSynced: "No successful cloud sync yet",
    cloudSyncUpgradeCta: "Unlock Cloud Sync",
    cloudSyncMonthlyCta: "Get Monthly Cloud Sync",
    cloudSyncAnnualCta: "Get Yearly Cloud Sync",
    cloudSyncRestoreCta: "Restore Purchase",
    cloudSyncRetryCta: "Retry pending sync",
    cloudSyncRetryDetail: "Replace cloud data with this device to finish pending sync.",
    cloudSyncSyncCta: "Push this device to cloud",
    cloudSyncSyncDetail: "Replace cloud data with this device, then refresh from cloud.",
    cloudSyncSyncConfirm: "Replace your cloud data with the records currently on this device?",
    cloudSyncSyncDone: "Cloud replaced with {count} local records.",
    cloudSyncSyncFailed: "Cloud sync failed. Your local changes are still saved on this device.",
    cloudSyncPullCta: "Replace this device from cloud",
    cloudSyncPullDetail: "Discard pending local changes and download the latest cloud copy.",
    cloudSyncPullConfirm:
      "Replace the records on this device with the latest cloud data? Pending local changes on this device will be discarded.",
    cloudSyncPullDone: "Downloaded {count} cloud records to this device.",
    cloudSyncPullFailed: "Cloud download failed. Your current local data was kept.",
    iapNotReadyTitle: "Purchase not set up",
    iapNotReadyMessage:
      "Purchases are not configured for this build. Add RevenueCat keys and rebuild the app.",
    iapPackageUnavailableMessage: "This plan is not available in the current store offering.",
    iapErrorTitle: "Purchase failed",
    iapErrorMessage: "Please try again later.",
    localLimitTitle: "Local storage limit",
    localLimitValue: "{count} / {limit} records on this device",
    localLimitReachedTitle: "Limit reached",
    localLimitReachedMessage:
      "You reached the free local limit. Upgrade to Pro and sign in to unlock unlimited cloud storage.",
    localLimitReachedLocalOnlyMessage:
      "このビルドのローカル記録上限に達しました。このデバイスで使い続けるには、いくつかの記録を削除してください。",
    storageUpgradeTitle: "Upgrade Storage Plan",
    storageUpgradeSubtitle: "Compare Basic, Plus, and Pro storage options.",
    storageUpgradeEyebrow: "Storage",
    storageUpgradeIntro:
      "Choose the plan that fits how you keep records: free local use, unlimited local storage, or cloud sync for multiple devices and shared books.",
    storagePlanCurrentBasic: "Current plan: Basic",
    storagePlanCurrentPlus: "Current plan: Plus",
    storagePlanCurrentPro: "Current plan: Pro",
    storagePlanCurrentBadge: "Current",
    storagePlanBasicTitle: "Basic Free",
    storagePlanBasicPrice: "USD $0",
    storagePlanBasicDescription: "Start accounting for free without signing in.",
    storagePlanBasicFeatureLimit: "Up to 200 records stored locally on this device.",
    storagePlanBasicFeatureNoLogin: "No account required.",
    storagePlanPlusTitle: "Plus Local",
    storagePlanPlusPrice: "USD $14.99 one-time",
    storagePlanPlusDescription: "For privacy-first users who want unlimited local records without a subscription.",
    storagePlanPlusFeatureUnlimited: "Unlimited local records.",
    storagePlanPlusFeaturePrivate: "Data stays on this device with no cloud account required.",
    storagePlanProTitle: "Pro Cloud",
    storagePlanProPrice: "{monthly} or {annual}",
    storagePlanProMonthlyFallback: "USD $5.99/month",
    storagePlanProAnnualFallback: "USD $59/year",
    storagePlanProDescription: "For multiple devices, phone changes, couples, families, and shared expenses.",
    storagePlanProFeatureSync: "Unlimited cloud records with automatic sync.",
    storagePlanProFeatureRestore: "Sign in across devices and restore after switching phones.",
    storagePlanProFeatureShared: "Shared books, reimbursements, settlement flow, and separate personal/shared views.",
    storagePlanProFeatureTravel: "Travel accounting.",
    storageUpgradeActionsTitle: "Upgrade when you are ready",
    storageUpgradeProAnnualCta: "Start Pro yearly · {price}",
    storageUpgradeProMonthlyCta: "Start Pro monthly · {price}",
    storageUpgradePlusCta: "Get Plus · {price}",
    storageUpgradePlusComingSoon: "Plus one-time purchase coming soon",
    "features.cloud-backup-sync.title": "クラウドバックアップと同期",
    "features.cloud-backup-sync.message":
      "オプションのサインインでデバイス間で同期し、再インストール後にデータを復元できます。",
    "features.receipt-scan-ocr.title": "レシートスキャン + OCR",
    "features.receipt-scan-ocr.message":
      "レシートをスキャンして金額と店舗情報を自動入力します。",
    "features.export-pdf-spreadsheet.title": "PDF + スプレッドシートテンプレートへのエクスポート",
    "features.export-pdf-spreadsheet.message":
      "データをPDFにエクスポートし、スプレッドシートテンプレートを使用してより良い整理ができます。",
    comingSoon: "近日公開",
    dontShowAgain: "今後表示しない",
    expense: "支出",
    income: "収入",
    addExpense: "支出を追加",
    addIncome: "収入を追加",
    smartLogExpense: "スマート支出記録",
    smartLogIncome: "スマート収入記録",
    suggestedNames: "候補名",
    moneyFlowQuestion: "お金はどこに使われていますか？",
    timeQuestion: "この期間の推移はどうですか？",
    pie: "円グラフ",
    treemap: "ツリーマップ",
    bar: "棒グラフ",
    line: "折れ線",
    spendingPie: "支出円グラフ",
    spendingTreemap: "支出ツリーマップ",
    periodCompare: "期間比較",
    spendingTrend: "支出推移",
    topFlow: "最大項目",
    dailyAverage: "1日平均",
    groups: "分類",
    noData: "データなし",
    errorOccurred: "エラーが発生しました",
    errorMessage: "予期しないエラーが発生しました。もう一度お試しいただくか、アプリを再起動してください。",
    tryAgain: "再試行",
    errorSaveFailed: "保存に失敗しました。もう一度お試しください。",
    errorDeleteFailed: "削除に失敗しました。もう一度お試しください。",
    errorLoadFailed: "データの読み込みに失敗しました。もう一度お試しください。",
    errorInvalidAmount: "ゼロより大きい有効な金額を入力してください。",
    errorAmountTooLarge: "金額が大きすぎます。最大値は {max} です。",
    errorDescriptionTooLong: "説明が長すぎます。最大 {max} 文字です。",
    errorNetworkFailed: "ネットワークエラー。接続を確認してください。",
    errorDatabaseFailed: "データベースエラー。アプリを再起動してください。",
    loading: "読み込み中...",
    editEntry: "編集",
    save: "保存",
    saving: "保存中...",
    type: "種類",
    delete: "削除",
    deleteEntry: "削除",
    deleteConfirmation: "このエントリを削除してもよろしいですか？",
    logDate: "記録日",
  },
};

const GLOSSARY_TRANSLATIONS: Record<ResolvedLanguage, Record<string, string>> = {
  en: GLOSSARY_TRANSLATION_EN,
  zh: GLOSSARY_TRANSLATION_ZH,
  es: GLOSSARY_TRANSLATION_ES,
  fr: GLOSSARY_TRANSLATION_FR,
  de: GLOSSARY_TRANSLATION_DE,
  ja: GLOSSARY_TRANSLATION_JA,
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("device");

  // Get the resolved language (actual language code used for translations)
  // Memoize to avoid recalculating device language on every render
  const resolvedLanguage: ResolvedLanguage = useMemo(() => {
    return language === "device" ? getDeviceLanguage() : language;
  }, [language]);

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const saved = await AsyncStorage.getItem(STORAGE_KEYS.LANGUAGE);
      if (saved && SUPPORTED_LANGUAGES.includes(saved as Language)) {
        setLanguageState(saved as Language);
      } else {
        setLanguageState("device");
      }
    } catch (error) {
      logger.error("Failed to load language", error);
      setLanguageState("device");
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem(STORAGE_KEYS.LANGUAGE, lang);
      setLanguageState(lang);
    } catch (error) {
      logger.error("Failed to save language", error);
    }
  };

  const t = useMemo(
    () =>
      (key: string): string => {
        return (
          translations[resolvedLanguage]?.[key] ||
          GLOSSARY_TRANSLATIONS[resolvedLanguage]?.[key] ||
          translations.en[key] ||
          GLOSSARY_TRANSLATIONS.en[key] ||
          key
        );
      },
    [resolvedLanguage]
  );

  const contextValue = useMemo(
    () => ({ language, resolvedLanguage, setLanguage, t }),
    [language, resolvedLanguage, t],
  );

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
